---
title: "multi-sites-treatment-effects"
author: "Xiulin Gao"
date: "2025-04-20"
output: html_document
---

```{r setup, include=FALSE}

home_path   = path.expand("~")
main_path   = file.path("/Volumes/Ldian/FATES/fuel-treatment-decomp-250620/3sites-comp")
util_path   = file.path(home_path,"Util/RUtils")
hlm_files   = c("blodgt-decomp_hlm1d.csv",
                "stef-decomp_hlm1d.csv",
                "tea-decomp_hlm1d.csv")
hlm_paths   = file.path(main_path,hlm_files)

pft_files  = c("blodgt-decomp_bypft-dbh15.csv",
               "stef-decomp_bypft-dbh15.csv",
               "tea-decomp_bypft-dbh15.csv")
pft_paths   = file.path(main_path,pft_files)

ddbh_pft_files = c("blodgt-decomp_bypft-dbh10.csv",
                   "stef-decomp_bypft-dbh10.csv",
                   "tea-decomp_bypft-dbh5.csv")
ddbh_paths = file.path(main_path,ddbh_pft_files)


dbh_files  = c("blodgt-decomp_bydbh.csv",
               "stef-decomp_bydbh.csv",
               "tea-decomp_bydbh.csv")
dbh_paths   = file.path(main_path,dbh_files)
fuel_files = c("blodgt-decomp_byfuel.csv",
               "stef-decomp_byfuel.csv",
               "tea-decomp_byfuel.csv")
fuel_paths   = file.path(main_path,fuel_files)

ddbh_szpf_files = c("blodgt-decomp_ddbh_szpf.csv",
                    "stef-decomp_ddbh_szpf.csv",
                    "tea-decomp_ddbh_szpf.csv")
ddbh_szpf_paths = file.path(main_path,ddbh_szpf_files)

nsites = length(fuel_paths)

case_desc = c("Blodgett-Control",
              "Blodgett-Thin",
              "Blodgett-Burn-Cool",
              "Blodgett-Burn-Hot",
              "STEF-Control",
              "STEF-Thin",
              "STEF-Burn-Cool",
              "STEF-Burn-Hot",
              "Teakettle-Control",
              "Teakettle-Thin",
              "Teakettle-Burn-Cool",
              "Teakettle-Burn-Hot")
names(case_desc) = c("1","2","3","4","5","6","7","8","9","10","11","12")
ncase = length(case_desc)/nsites

```





```{r ObservationData}

obs_main = file.path("Sierra-mixedConifer-project/data/Benchmarking_data/Benchmarks")
obs_path = file.path(home_path,obs_main)
ba_obs = c("basal_area_Blodgett.csv",
           "basal_area_STEF.csv",
           "basal_area_Teakettle.csv")
nplant_obs = c("stand_density_Blodgett.csv",
               "stand_density_STEF.csv",
               "stand_density_Teakettle.csv")
ctrl_growth_obs = c("growth_by_size_pft_Blodgett.csv",
                    "growth_by_size_pft_STEF.csv",
                    "growth_by_size_pft_Teakettle.csv")
delta_growth_obs = c("growth_effects_Blodgett.csv",
                     "growth_effects_STEF.csv",
                     "growth_effects_Teakettle.csv")
mort_obs = c("mortality_Blodgett.csv",
             "mortality_STEF.csv",
             "mortality_Teakettle.csv")
sz_obs = c("size_dist_Blodgett.csv",
           "size_dist_STEF.csv",
           "size_dist_Teakettle.csv")
fuel_obs = c("fuels_Blodgett.csv",
             "fuels_STEF.csv",
             "fuels_Teakettle.csv")
prepost_ba_obs = c("prepost_basal_area_Blodgett.csv",
                   "prepost_basal_area_STEF.csv",
                   "prepost_basal_area_Teakettle.csv")
prepost_sd_obs = c("prepost_stand_density_Blodgett.csv",
                   "prepost_stand_density_STEF.csv",
                   "prepost_stand_density_Teakettle.csv")
prepost_szdist_obs = c("prepost_size_dist_Blodgett.csv",
                       "prepost_size_dist_STEF.csv",
                       "prepost_size_dist_Teakettle.csv")
prepost_fuel_obs = c("prePost_fuels_Teakettle.csv")


ba_path = file.path(obs_path,ba_obs)
nplant_path = file.path(obs_path,nplant_obs)
delta_growth_path = file.path(obs_path,delta_growth_obs)
ctrl_growth_path  = file.path(obs_path,ctrl_growth_obs)
mort_path = file.path(obs_path,mort_obs)
sz_path = file.path(obs_path,sz_obs)
fuel_path = file.path(obs_path,fuel_obs)
diff_ba_path = file.path(obs_path,prepost_ba_obs)
diff_sd_path = file.path(obs_path,prepost_sd_obs)
diff_szdist_path = file.path(obs_path,prepost_szdist_obs)
diff_fuel_path = file.path(obs_path,prepost_fuel_obs)



```



```{r MakeDir}

#plot path
plot_main  = file.path(main_path,"Figures")
# Output path for time series
pft_path     = file.path(plot_main,"Effects-PFT"     )
size_path    = file.path(plot_main,"Effects-DBH"     )
mean_path    = file.path(plot_main,"Effects-Mean"    )
bncmark_path = file.path(plot_main,"Benchmark")

# Create paths for time series
dummy = dir.create(pft_path    , recursive = TRUE, showWarnings = FALSE)
dummy = dir.create(size_path   , recursive = TRUE, showWarnings = FALSE)
dummy = dir.create(mean_path   , recursive = TRUE, showWarnings = FALSE)
dummy = dir.create(bncmark_path, recursive = TRUE, showWarnings = FALSE)

```



```{r Packages}
library(ggplot2)
library(tidyverse)
library(lubridate)
library(data.table)
library(patchwork)


```



```{r UserPFTFuelInfo}
## PFT info
user_pftinfo  = TRUE

# List of PFTs, in case user_pftinfo is TRUE
n            = 0
pftinfo      = list()
n            = n + 1
pftinfo[[n]] = list( id     = 1
                     , key    = "pft1"
                     , short  = "Pine"
                     , desc   = "Pine tree"
                     , colour = "#74A089"
                     , parse  ="P*i*n*e[E*v*g*r*n]"
)
n            = n + 1
pftinfo[[n]] = list( id     = 2
                     , key    = "pft2"
                     , short  = "Cedar"
                     , desc   = "Incense cedar"
                     , colour = "#9A8822"
                     , parse  ="C*e*d*a*r[E*v*g*r*n]"
)       
n            = n + 1
pftinfo[[n]] = list( id     = 3
                     , key    = "pft3"
                     , short  = "Fir"
                     , desc   = "White fir"
                     , colour = "#F8AFA8"
                     , parse  ="F*i*r[E*v*g*r*n]"
) 
n            = n + 1
pftinfo[[n]] = list( id     = 4
                     , key    = "pft4"
                     , short  = "Oak"
                     , desc   = "Black oak"
                     , colour = "#FDDDA0"
                     , parse  ="F*i*r[E*v*g*r*n]"
) #end of PFT list

pftinfo  = do.call(what=rbind,args=lapply(X=pftinfo,FUN=as_tibble,stringsAsFactors=FALSE))
npfts = nrow(pftinfo)


# List of fuels, in case user_fuleinfo is TRUE
n               = 0
fuelinfo        = list()
n               = n + 1
fuelinfo[[n]]   = list( id      = 1
                      , key     = "fuel1"
                      , short   = "Twig"
                      , desc    = "Fuel from twig" 
                      , colour  = "#E69F00"
                      , parse   = "F*u*e*l[T*w*i*g]")
n               = n + 1
fuelinfo[[n]]   = list( id      = 2
                      , key     = "fuel2"
                      , short   = "SBranch"
                      , desc    = "Fuel from small branch" 
                      , colour  = "#56B4E9"
                      , parse   = "F*u*e*l[S*b*r*a*n*c*h]")
n               = n + 1
fuelinfo[[n]]   = list( id      = 3
                      , key     = "fuel3"
                      , short   = "LBranch"
                      , desc    = "Fuel from large branch" 
                      , colour  = "#0072B2"
                      , parse   = "F*u*e*l[L*b*r*a*n*c*h]")
n               = n + 1
fuelinfo[[n]]   = list( id      = 4
                      , key     = "fuel4"
                      , short   = "Trunk"
                      , desc    = "Fuel from trunk" 
                      , colour  = "#D55E00"
                      , parse   = "F*u*e*l[T*r*u*n*k]")
n               = n + 1
fuelinfo[[n]]   = list( id      = 5
                      , key     = "fuel5"
                      , short   = "DeadLeaf"
                      , desc    = "Fuel from dead leaf" 
                      , colour  = "#999999"
                      , parse   = "F*u*e*l[D*l*e*a*f]")
n               = n + 1
fuelinfo[[n]]   = list( id      = 6
                      , key     = "fuel6"
                      , short   = "LiveGrass"
                      , desc    = "Fuel from live grass" 
                      , colour  = "#009E73"
                      , parse   = "F*u*e*l[L*g*r*a*s*s]") #end of fuel list

fuelinfo  = do.call(what=rbind,args=lapply(X=fuelinfo,FUN=as_tibble,stringsAsFactors=FALSE))
nfuels = nrow(fuelinfo)

```




```{r DBHInfo}

ndbhs = 13
dbh_lwr = c(0,5,10,15,20,30,40,50,60,70,80,90,100)
dbh_upr = c(dbh_lwr[-1],dbh_lwr[ndbhs]+2*max(diff(dbh_lwr)))
dbh_labs = c( paste0("paste(",dbh_lwr[-ndbhs],"-",dbh_upr[-ndbhs],")")
                        , paste0("paste(",dbh_lwr[ ndbhs],"-infinity)"))
dbh_desc = c( paste0("paste(paste(",dbh_lwr[-ndbhs],"<=D*B*H)<",dbh_upr[-ndbhs],"*c*m)")
                          , paste0("paste( D*B*H >=",dbh_lwr[ndbhs],"*c*m)"))

dbh_labs_10     = c(dbh_labs[5:13], "paste(10-20)")
dbh_labs_10    = parse(text=dbh_labs_10)
names(dbh_labs_10) = c("5","6","7","8","9","10","11","12","13","4")

dbh_labs = parse(text=dbh_labs)
dbh_labs_10 = parse(text=dbh_labs_10)


```





```{r PlotSettings}

gg_device  = c("png")     # Output devices to use (Check ggsave for acceptable formats)
gg_depth   = 600          # Plot resolution (dpi)
gg_ptsz    = 18           # Font size
gg_ptszl   = 26
gg_width   = 17.5         # Plot width (units below)
gg_widthn  = 14.5
gg_height  = 8.5          # Plot height (units below)
gg_units   = "in"         # Units for plot size
gg_screen  = FALSE         # Show plots on screen as well?
gg_tfmt    = "%Y"         # Format for time strings in the time series %Y: 4 DIGITS YEAR %y 2 digits year
gg_ncolours    = 129      # Number of node colours for heat maps.
gg_fleg        = 1./6.    # Fraction of plotting area dedicated for legend
gg_dstat_thick = 0.1      # Thickess for the drought-deciduous status band in the stress overview plot (Value


ens_colour = c("#A0AE6A", "#836B43", "#D68D18", "#437683", "#18B0D6")

top12 <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288", "#AA4499", 
           "#44AA99", "#999933", "#882255", "#6699CC", "#888888", "#661100")

site_colour  = "#000000"

ndevice = length(gg_device)


# Define lower and upper bound for interannual variability ribbon around the mean.
sdev_ribbon  = 1.                  # Standard-deviation equivalent for ribbon 
qlwr_ribbon  = pnorm(-sdev_ribbon) # Lower quantile for ribbon
qupr_ribbon  = pnorm(+sdev_ribbon) # Lower quantile for ribbon
alpha_ribbon = 0.2

```





```{r Constants}
month_2_sec = 2628000
ha_2_m2 = 10000
mgha_2_kgm2 = 0.1
mass_2_carbon = 0.45

```




```{r ReadAndAppend}
ReadAppend_fun = function(path,n_site,n_case,case_desc){
  return_df = NULL
  for (s in sequence(n_site)){
   case_up = s * n_case
   case_lw = (s-1)*n_case + 1
   case_now = c(case_lw:case_up)
   df_now = data.table::fread(path[s])
   df_now = df_now          %>% 
            dplyr::mutate(case = case_when(case==1 ~ case_now[1],
                                          case==2 ~ case_now[2],
                                          case==3 ~ case_now[3],
                                          case==4 ~ case_now[4]),
                         desc = case_desc[case])
   
   if(is.null(return_df)){
     return_df = df_now
   }else{
     return_df = rbind(return_df,df_now,fill=TRUE)
   }
  }
  return(return_df)
  
}
all_model_paths = c("hlm_paths","pft_paths","ddbh_paths","dbh_paths","fuel_paths","ddbh_szpf_paths")
model_file_name = c("hlm1d-3sites.csv","bypft-3sites.csv","ddbh-3sites.csv","bydbh-3sites.csv","byfuel-3sites.csv",
                    "ddbh-byszpf-3sites.csv")
n_path = length(all_model_paths)
for(p in sequence(n_path)){
  p_now = get(all_model_paths[p])
  f_now = model_file_name[p]
  df_now = ReadAppend_fun(p_now,nsites,ncase,case_desc)
  data.table::fwrite(df_now,file=file.path(main_path,f_now))
}





```





```{r SomeFunctions}
rename_fun = function(x){
  x = gsub(pattern="fates_",replacement = "ctrl_",x)
}

ddbh_scale_fun = function(df,x){
  if(grepl("ddbh_canopy",x)){denominator = ifelse(grepl("fates",x),"fates_nplant_canopy","ctrl_nplant_canopy")}
  else if(grepl("ddbh_ustory",x)){denominator = ifelse(grepl("fates",x),"fates_nplant_ustory","ctrl_nplant_ustory")}
  else{denominator = ifelse(grepl("fates",x),"fates_nplant","ctrl_nplant")}
  df[[x]] = df[[x]]/df[[denominator]]
}

delta_pct_fun = function(df,x,quant_up,quant_lw){
  ctrl_name = rename_fun(x)
  df[[x]] = (df[[x]] - df[[ctrl_name]]) / df[[ctrl_name]] * 100
  df[[x]] = ifelse(df[[x]]==Inf, NA, df[[x]])
  up_thresh = quantile(df[[x]],quant_up,na.rm=TRUE)
  lw_thresh = quantile(df[[x]],quant_lw,na.rm=TRUE)
  df[[x]] = ifelse(df[[x]] > up_thresh | df[[x]] < lw_thresh, NA, df[[x]])
}


delta_fun = function(df,x){
  ctrl_name = rename_fun(x)
  df[[x]] = df[[x]] - df[[ctrl_name]]
}

site_grab = function(desc){
  site = sub("-.*","",desc) 
}

treatment_grab = function(desc){
  if(grepl("[0-9]+-BA[0-9]+",desc)){treat = "Thin"}
  else if(grepl("Rx-Inclusive",desc)){treat="Burn-Cool"}
  else if(grepl("Rx-Selective",desc)){treat="Burn-Hot"}
  else{treat = "None"}
 # treat = if_else(grepl("[0-9]+-BA",desc),"Logging","Rx-fire")
}

treatment_grab = function(desc){
  if(grepl("Thin",desc)){treat = "Thin"}
  else if(grepl("Burn-Cool",desc)){treat="Burn-Cool"}
  else if(grepl("Burn-Hot",desc)){treat="Burn-Hot"}
  else{treat = "None"}
 # treat = if_else(grepl("[0-9]+-BA",desc),"Logging","Rx-fire")
}

find_mort = function(x,n){
   mort_mon = ifelse( test = n == 0, yes = NA, no = pmin(1.,x/n/12.))
   mort_year = ifelse(is.na(mort_mon),NA, 100. * (1. - (1. - mort_mon)^12))
   return(mort_year)
}#end function find_mort

rename_sd = function(x){
   x = gsub(pattern="fates_",replacement = "sd_",x)
}

CI95_error = function(n, mean, sd) {
  se = sd/sqrt(n)
  df = n - 1
  alpha = 0.05
  t_score = qt(alpha/2,df=df,lower.tail = FALSE)
  margin_error = t_score * se
}

zero_to_na = function(x){
  x=ifelse(x==0,NA,x)
}

na_to_zero = function(x){
  x=ifelse(is.na(x),0,x)
}


post_rename = function(x){
   x = gsub(pattern="fates_",replacement = "post_",x)
}

prepost_pct_diff = function(df,x){
  post_name = post_rename(x)
  df[[x]] = (df[[post_name]] - df[[x]]) / df[[x]]*100
}



```





```{r ByPFTDataProcessing}

bypft = data.table::fread(file.path(main_path,model_file_name[2]))
bypft = bypft                    %>% 
        dplyr::select(-c(fates_mortality_cambialburn,
                 fates_mortality_crownscorch,
                 fates_mortality_rxcambial,
                 fates_mortality_rxcrown))
mortout_pft    = names(bypft)[grep(pattern="mortality",x=names(bypft))]
bypft  =     bypft                                              %>% 
             mutate(month = month(time)
                   ,year  = year(time))                         %>% 
             mutate_at(c(mortout_pft),
                       ~ find_mort(x=.x,
                                   n= ifelse(.x=="fates_mortality_ustory", 
                                                   .data$fates_nplant_ustory, 
                                                   .data$fates_nplant)))
bypft$fates_mortality = bypft %>% dplyr::select(starts_with("fates_mortality")) %>% rowSums()



## excluding growth rate of plants died
## in the calculation of averaged growth rate
## by setting its growth rate to N/A

bypft_na = bypft                     %>% 
mutate(fates_ddbh_canopy = ifelse(is.na(fates_nplant_canopy) | fates_nplant_canopy==0,
                           NA, fates_ddbh_canopy*ha_2_m2),
       fates_ddbh_ustory = ifelse(is.na(fates_nplant_ustory) | fates_nplant_ustory==0,
                           NA, fates_ddbh_ustory*ha_2_m2),
       fates_ddbh        = ifelse(is.na(fates_nplant) | fates_nplant==0, 
                           NA, fates_ddbh*ha_2_m2),
       fates_nplant_canopy = ifelse(fates_nplant_canopy==0, NA, fates_nplant_canopy),
       fates_nplant_ustory = ifelse(fates_nplant_ustory==0, NA, fates_nplant_ustory),
       fates_nplant        = ifelse(fates_nplant==0, NA, fates_nplant))

bypft_na = bypft_na                         %>% 
           dplyr::select(-c(time,month))    %>% 
           group_by(case,desc,year,pft)     %>%
           summarize_all(mean,na.tm=TRUE)   %>%
           ungroup()
  

ddbh_vars = names(bypft_na)[grepl("ddbh",names(bypft_na))]
n_ddbh = length(ddbh_vars)
for(v in sequence(n_ddbh)){
  var_now = ddbh_vars[v]
  bypft_na[[var_now]] = ddbh_scale_fun(bypft_na,var_now)
}

ctrl = bypft_na %>% filter(case %in% c(1,5,9))
ctrl = ctrl                    %>% 
       group_by(case,desc)     %>% 
       slice(rep(seq_len(n()),times = nsites)) %>% ungroup()

delta_vars = c("fates_nplant",
               "fates_nplant_ustory",
               "fates_ddbh",
               "fates_ddbh_canopy",
               "fates_ddbh_ustory",
               "fates_basalarea",
               "fates_mortality")
delta_desc = c("stem density",
               "understory stem density",
               "growth rate",
               "growth rate canopy",
               "growth rate understory",
               "basal area",
               "mortality")

n_delta = length(delta_vars)


ctrl_bypft =  ctrl                       %>% 
              dplyr::select(all_of(delta_vars)) %>% 
              rename_at(vars(fates_nplant:fates_mortality),rename_fun)

treat_bypft = bypft_na                                  %>% 
              filter(!case%in% c(1,5,9))             

treat_bypft = treat_bypft %>% dplyr::select(all_of(c("case",
                                              "year",
                                              "pft",
                                              "desc",
                                              delta_vars)))
    

delta_bypft = cbind(treat_bypft,ctrl_bypft)

delta_bypft = delta_bypft                    %>% 
              mutate(site=site_grab(desc))
delta_bypft$treatment = unlist(lapply(delta_bypft$desc,treatment_grab))


for(v in sequence(n_delta)){
  var_now = delta_vars[v]
  delta_bypft[[var_now]] = delta_pct_fun(delta_bypft,var_now,1,0)
}

treated_case = unique(delta_bypft$case)
delta_bypft = delta_bypft                                              %>% 
              mutate_at(vars(fates_nplant:fates_mortality),zero_to_na) %>% 
              filter(!is.na(fates_nplant))


#rx_date  =  bypft                                 %>% 
#            filter(fates_mortality_rxfire>0)      %>% 
#            select(case,time)                     %>% 
#            distinct()                            %>% 
#            rename(rx_date = time)                %>% 
#            group_by(case)                        %>% 
#            mutate(lag_rxdate = rx_date - lag(rx_date),
#                   lag_rxdate = as.numeric(lag_rxdate)/month_2_sec)

#twofires_last = which(rx_date$lag_rxdate<2)
#rx_date = rx_date[-(twofires_last-1), ]
#ls_date = as.POSIXct("2020-12-01",tz="UTC")
#rx_delta = delta_bypft %>% filter(case %in% unique(rx_date$case))
#rx_cases = unique(rx_delta$case)

deltabypft_mean = NULL
deltabypft_sd   = NULL
deltabypft_se   = NULL

for(n in treated_case){
  delta_now = delta_bypft %>% filter(case==n)
 
  #breaks_now = rx_date$rx_date[rx_date$case==n]
  #breaks_now = c(breaks_now,ls_date)
  #n_bk = length(breaks_now)-1
  #labels = sprintf("RX%i",sequence(n_bk))
    mean_pft  = delta_now                                                 %>% 
               #mutate(RXtrt_grp = cut(time,breaks = breaks_now,labels))  %>% 
               #filter(!is.na(RXtrt_grp))                                 %>%
               dplyr::select(-c(year,case,desc))                                %>% 
               group_by(site,treatment,pft)                              %>% 
               summarize_all(mean,na.rm=TRUE)
    
    deltabypft_mean = rbind(deltabypft_mean,mean_pft)
    
    sd_pft  = delta_now                                                 %>% 
               #mutate(RXtrt_grp = cut(time,breaks = breaks_now,labels))  %>% 
               #filter(!is.na(RXtrt_grp))                                 %>%
               dplyr::select(-c(year,case,desc))                                %>% 
               group_by(site,treatment,pft)                              %>% 
               summarize_all(sd,na.rm=TRUE)
     deltabypft_sd = rbind(deltabypft_sd,sd_pft)
     
     se_pft = delta_now                    %>% 
              select(-c(year,case,desc))   %>% 
              group_by(site,treatment,pft) %>% 
              summarize_all(funs(se=sd(.)/sqrt(n())))
     deltabypft_se = rbind(deltabypft_se,se_pft)
    
     
}



```




```{r PlotDeltaByPFTAndTreatment, echo=FALSE}


plot_df = deltabypft_mean
plot_df$pft = factor(plot_df$pft,levels=unique(plot_df$pft))
f_colpfts   = pftinfo$colour
f_pftlabs   = pftinfo$short
names(f_pftlabs) = c("1","2","3","4")

for(d in sequence(n_delta)){
  f_vnam = delta_vars[d]
  se_nam = paste0(f_vnam,"_se")
  f_desc = delta_desc[d]
  plot = ggplot(plot_df,aes_string(x = "site",y=f_vnam,
                   ymin=plot_df[[f_vnam]]-deltabypft_se[[se_nam]],
                   ymax=plot_df[[f_vnam]]+deltabypft_se[[se_nam]],
                   colour="treatment")) +
       facet_wrap(.~pft,labeller=labeller(pft=f_pftlabs),scales="free_x")+
       geom_point(size=2) +
       geom_errorbar(width=0)+
       geom_hline(yintercept = 0, color="black",linetype=2)+
       coord_flip() +
       #scale_colour_manual(values=f_colpfts,labels=f_pftlabs) +
       scale_colour_manual(values=c("Burn-Cool" = "#836B43",
                                    "Burn-Hot" = "#D68D18",
                                    "Thin" = "#A0AE6A")) +
       ylab(paste0("Relative change in ", f_desc," (%)")) +
       xlab("") +
       theme_grey( base_size = gg_ptsz, base_family = "Helvetica",base_line_size = 0.5,base_rect_size =0.5) +
       theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+
  
  
  for (d in sequence(ndevice)){
    f_output = paste0(f_vnam,"_PFTSplit-15-SE-NA.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = plot
                    , device   = gg_device[d]
                    , path     = pft_path
                    , width    = gg_widthn*0.5
                    , height   = gg_height*0.6
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
   }
       

  
}

```




```{r OverallEffectDataProcessing}

overall = data.table::fread(file.path(main_path,model_file_name[2]))
overall = overall                        %>% 
          group_by(case,desc,time)       %>% 
          dplyr::select(-pft)            %>% 
          summarize_all(sum,na.rm=TRUE)  %>% 
          ungroup()

overall = overall                                    %>% 
          dplyr::select(-c(fates_mortality_cambialburn,
                    fates_mortality_crownscorch,
                    fates_mortality_rxcambial,
                    fates_mortality_rxcrown))

overall = overall                                 %>% 
          mutate(month = month(time)
                ,year  = year(time))              %>% 
             mutate_at(c(mortout_pft),
                       ~ find_mort(x=.x,
                                   n= ifelse(.x=="fates_mortality_ustory", 
                                                   .data$fates_nplant_ustory, 
                                                   .data$fates_nplant)))
overall$fates_mortality = overall %>% dplyr::select(starts_with("fates_mortality")) %>% rowSums()



overall_na  = overall                    %>% 
  mutate(fates_ddbh_canopy = ifelse(is.na(fates_nplant_canopy) | fates_nplant_canopy==0,
                             NA, fates_ddbh_canopy*ha_2_m2),
         fates_ddbh_ustory = ifelse(is.na(fates_nplant_ustory) | fates_nplant_ustory==0,
                             NA, fates_ddbh_ustory*ha_2_m2),
         fates_ddbh        = ifelse(is.na(fates_nplant) | fates_nplant==0, 
                             NA, fates_ddbh*ha_2_m2),
         fates_nplant_canopy = ifelse(fates_nplant_canopy==0, NA, fates_nplant_canopy),
         fates_nplant_ustory = ifelse(fates_nplant_ustory==0, NA, fates_nplant_ustory),
         fates_nplant        = ifelse(fates_nplant==0, NA, fates_nplant))

overall_na  = overall_na                     %>% 
              group_by(case,desc,year)       %>% 
              dplyr::select(-c(time,month))  %>% 
              summarize_all(mean,na.rm=TRUE) %>% 
              ungroup()


ddbh_vars = names(overall_na)[grepl("ddbh",names(overall_na))]
n_ddbh = length(ddbh_vars)
for(v in sequence(n_ddbh)){
  var_now = ddbh_vars[v]
  overall_na[[var_now]] = ddbh_scale_fun(overall_na,var_now)
}

ctrl_all = overall_na %>% filter(case %in% c(1,5,9))
ctrl_all = ctrl_all                %>% 
           group_by(case,desc)     %>% 
           slice(rep(seq_len(n()),times = nsites)) %>% ungroup()

ctrl_all =  ctrl_all                              %>% 
            dplyr::select(all_of(delta_vars))     %>% 
            rename_at(vars(fates_nplant:fates_mortality),rename_fun)

treat_all = overall_na                            %>% 
            filter(!case%in% c(1,5,9))             

treat_all = treat_all %>% dplyr::select(all_of(c("case",
                                          "year",
                                          "desc",
                                        delta_vars)))
    

delta_treat = cbind(treat_all,ctrl_all)
delta_treat = delta_treat                   %>% 
              mutate(site=site_grab(desc))
delta_treat$treatment = unlist(lapply(delta_treat$desc,treatment_grab))


for(v in sequence(n_delta)){
  var_now = delta_vars[v]
  delta_treat[[var_now]] = delta_pct_fun(delta_treat,var_now,1,0)
}

delta_treat = delta_treat                           %>% 
              mutate_at(vars(fates_nplant:fates_mortality),
                         zero_to_na)                %>% 
              filter(!is.na(fates_nplant))
delta_mean = NULL
delta_sd   = NULL
delta_se   = NULL

for(n in treated_case){
  delta_now = delta_treat %>% filter(case==n)
  mean_now  = delta_now                                             %>% 
              dplyr::select(-c(year,case,desc))                     %>% 
              group_by(site,treatment)                              %>% 
              summarize_all(mean,na.rm=TRUE)
    
    delta_mean = rbind(delta_mean,mean_now)
    
    sd_now  =  delta_now                                             %>% 
               dplyr::select(-c(year,case,desc))                     %>% 
               group_by(site,treatment)                              %>% 
               summarize_all(sd,na.rm=TRUE)
    delta_sd = rbind(delta_sd,sd_now)
    
    se_now  = delta_now                       %>% 
              select(-c(year,case,desc))      %>% 
              group_by(site,treatment)        %>% 
              summarize_all(funs(se=sd(.)/sqrt(n())))
    delta_se = rbind(delta_se,se_now)
    
    
    
     
}







```





```{r PlotDeltaByTreatment, echo=FALSE}


plot_df = delta_mean

for(d in sequence(n_delta)){
  f_vnam = delta_vars[d]
  se_nam = paste0(f_vnam,"_se")
  f_desc = delta_desc[d]
  plot = ggplot(plot_df,aes_string(x = "site",y=f_vnam,
                   ymin=plot_df[[f_vnam]]-delta_se[[se_nam]],
                   ymax=plot_df[[f_vnam]]+delta_se[[se_nam]],
                   colour="treatment")) +
       geom_point(size=2) +
       geom_errorbar(width=0)+
       geom_hline(yintercept = 0, color="black",linetype=2)+
       coord_flip() +
       scale_colour_manual(values=c("Burn-Cool" = "#836B43",
                                    "Burn-Hot" = "#D68D18",
                                    "Thin" = "#A0AE6A")) +
       ylab(paste0("Relative change in ", f_desc," (%)")) +
       xlab("") +
       theme_grey( base_size = gg_ptsz, base_family = "Helvetica",base_line_size = 0.5,base_rect_size =0.5) +
       theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+
  
  
  for (d in sequence(ndevice)){
    f_output = paste0(f_vnam,"_byTreatment-SE-NA.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = plot
                    , device   = gg_device[d]
                    , path     = mean_path
                    , width    = gg_widthn*0.5
                    , height   = gg_height*0.4
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
   }
       

  
}



```





```{r DeltaGrowthByDBHDataProcessing}

bydbh = data.table::fread(file.path(main_path,model_file_name[4]))
mortout_dbh = names(bydbh)[grepl(pattern="mortality",names(bydbh))]

bydbh = bydbh                                      %>% 
            mutate(year  = year(time),
                   month = month(time))            %>% 
             mutate_at(c(mortout_dbh),
                       ~ find_mort(x=.x,
                                   n= ifelse(.x=="fates_mortality_ustory", 
                                                   .data$fates_nplant_ustory, 
                                                   .data$fates_nplant)))

bydbh_na = bydbh                                          %>% 
           mutate(fates_ddbh_canopy = ifelse(is.na(fates_nplant_canopy) | fates_nplant_canopy==0,
                                      NA, fates_ddbh_canopy*ha_2_m2),
                  fates_ddbh_ustory = ifelse(is.na(fates_nplant_ustory) | fates_nplant_ustory==0,
                                      NA, fates_ddbh_ustory*ha_2_m2),
                  fates_ddbh        = ifelse(is.na(fates_nplant) | fates_nplant==0, 
                                      NA, fates_ddbh*ha_2_m2),
                  fates_nplant_canopy = ifelse(fates_nplant_canopy==0, NA, fates_nplant_canopy),
                  fates_nplant_ustory = ifelse(fates_nplant_ustory==0, NA, fates_nplant_ustory),
                  fates_nplant        = ifelse(fates_nplant==0, NA, fates_nplant))


bydbh_na = bydbh_na                          %>% 
           dplyr::select(-time)              %>% 
           group_by(case,desc,year,dbh)      %>% 
           summarize_all(mean,na.rm=TRUE)    %>% 
           ungroup()

ddbh_vars = names(bydbh_na)[grepl("ddbh",names(bydbh_na))]
n_ddbh = length(ddbh_vars)
for(v in sequence(n_ddbh)){
  var_now = ddbh_vars[v]
 bydbh_na[[var_now]] = ddbh_scale_fun(bydbh_na,var_now)
}


ctrl_growth = bydbh_na %>% filter(case %in% c(1,5,9))
ctrl_growth = ctrl_growth                    %>% 
              group_by(case,desc)            %>% 
              slice(rep(seq_len(n()),times = nsites)) %>% ungroup()


growth_vars = c("fates_ddbh",
               "fates_ddbh_canopy",
               "fates_ddbh_ustory")
growth_desc = c(
               "growth rate",
               "growth rate canopy",
               "growth rate understory")

n_delta = length(growth_vars)


ctrl_growth =  ctrl_growth                     %>% 
               select(all_of(growth_vars))     %>% 
               rename_at(vars(fates_ddbh:fates_ddbh_ustory),rename_fun)

treat_growth = bydbh_na                                  %>% 
               filter(!case%in% c(1,5,9))             

treat_growth = treat_growth %>% select(all_of(c("case",
                                                "year",
                                                "dbh",
                                                "desc",
                                              growth_vars)))
    

delta_growth = cbind(treat_growth,ctrl_growth)

delta_growth = delta_growth                    %>% 
               mutate(site=site_grab(desc))
delta_growth$treatment = unlist(lapply(delta_growth$desc,treatment_grab))

for(v in sequence(n_delta)){
  var_now = growth_vars[v]
  delta_growth[[var_now]] = delta_pct_fun(delta_growth,var_now,0.95,0.05)
}

delta_growth = delta_growth                    %>% 
               select(all_of(c("site",
                               "treatment",
                               "dbh",
                               "case",
                               growth_vars)))


delta_growth_12 = delta_growth %>% filter(dbh!=1)

delta_growth_12 = delta_growth_12                  %>% 
                  mutate_at(vars(fates_ddbh:fates_ddbh_ustory),
                            zero_to_na)            %>% 
                  filter(!is.na(fates_ddbh))

deltagrowth_mean = NULL
deltagrowth_sd   = NULL
deltagrowth_se   = NULL

for(n in treated_case){
  delta_now = delta_growth_12 %>% filter(case==n)
 
  mean_growth  = delta_now                                              %>% 
              group_by(site,treatment,dbh)                              %>% 
              select(-case)                                             %>%
              summarize_all(mean,na.rm=TRUE)
    
  deltagrowth_mean = rbind(deltagrowth_mean,mean_growth)
    
  sd_growth  = delta_now                                                 %>% 
               group_by(site,treatment,dbh)                              %>% 
               select(-case)                                             %>% 
               summarize_all(sd,na.rm=TRUE)
  deltagrowth_sd = rbind(deltagrowth_sd,sd_growth)
  
  se_growth  = delta_now                                                 %>% 
               group_by(site,treatment,dbh)                              %>% 
               select(-case)                                             %>% 
               summarize_all(funs(se=sd(.)/sqrt(n())))
  deltagrowth_se = rbind(deltagrowth_se,se_growth)
    
     
}




```





```{r PlotDeltaGrowthBySize}

plot_df = delta_growth_12
plot_df$dbh = factor(plot_df$dbh,levels=unique(plot_df$dbh))

for(d in sequence(n_delta)){
  f_vnam = growth_vars[d]
  f_desc = growth_desc[d]
  plot = ggplot(plot_df,aes_string(x = "dbh",y=f_vnam,
                   colour="treatment")) +
       facet_wrap(.~site)+#,scales="free")+
       geom_boxplot(outlier.shape = NA) +
       geom_hline(yintercept = 0, color="black",linetype=2)+
       scale_x_discrete(labels=dbh_labs[2:13]) +
       scale_colour_manual(values=c("Burn-Cool" = "#836B43",
                                    "Burn-Hot" = "#D68D18",
                                    "Thin" = "#A0AE6A")) +
       ylab(paste0("Relative change in ", f_desc," (%)")) +
       xlab("") +
       theme_grey( base_size = gg_ptsz, base_family = "Helvetica",base_line_size = 0.5,base_rect_size =0.5) +
       theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , angle  = 90
                                              , hjust  = 1
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+
  
  
  for (d in sequence(ndevice)){
    f_output = paste0(f_vnam,"_deltabySZ-smoothed-zero.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = plot
                    , device   = gg_device[d]
                    , path     = size_path
                    , width    = gg_widthn*0.8
                    , height   = gg_height*0.7
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
   }
       

  
}


```





```{r DeltaSizeDistributionProcessing}

sz_model = bydbh                           %>% 
           select(case,desc,time,dbh,
                  fates_nplant,
                  fates_nplant_canopy,
                  fates_nplant_ustory)     %>% 
           mutate(fates_nplant = ifelse(fates_nplant==0, NA, fates_nplant),
                  fates_nplant_canopy = ifelse(fates_nplant_canopy==0, NA, fates_nplant_canopy),
                  fates_nplant_ustory = ifelse(fates_nplant_ustory==0, NA, fates_nplant_ustory))
sz_model = sz_model                        %>% 
           mutate(year=year(time))         %>% 
           select(-time)                   %>% 
           group_by(case,desc,year,dbh)    %>% 
           summarize_all(mean,na.rm=TRUE)  %>% 
           ungroup()                       %>% 
           filter(!dbh%in%c(1,2,3))

sz_ctrl = sz_model %>% filter(case %in% c(1,5,9))
sz_ctrl = sz_ctrl                    %>% 
          group_by(case,desc)        %>% 
          slice(rep(seq_len(n()),times = nsites)) %>% ungroup()

delta_szvar = c("fates_nplant",
               "fates_nplant_ustory",
               "fates_nplant_canopy")
sz_desc = c("stem density",
            "understory stem density",
            "canopy stem density")

n_delta = length(delta_szvar)


sz_ctrl = sz_ctrl                             %>% 
          dplyr::select(all_of(delta_szvar))     %>% 
          rename_at(vars(fates_nplant:fates_nplant_canopy),rename_fun)

treat_sz = sz_model                           %>% 
           filter(!case%in% c(1,5,9))             

treat_sz = treat_sz %>% dplyr::select(all_of(c("case",
                                               "year",
                                               "dbh",
                                               "desc",
                                              delta_szvar)))
    

delta_sz = cbind(treat_sz,sz_ctrl)

delta_sz = delta_sz                    %>% 
           mutate(site=site_grab(desc))
delta_sz$treatment = unlist(lapply(delta_sz$desc,treatment_grab))


for(v in sequence(n_delta)){
  var_now = delta_szvar[v]
  delta_sz[[var_now]] = delta_pct_fun(delta_sz,var_now,0.9,0.1)
}

delta_sz  = delta_sz                        %>% 
            mutate_at(vars(fates_nplant:fates_nplant_canopy),
                      zero_to_na)          
            

treated_case = unique(delta_sz$case)

delta_szdist_mean = NULL
delta_szdist_sd   = NULL
delta_szdist_se   = NULL

for(n in treated_case){
  delta_now = delta_sz %>% filter(case==n)

    mean_sz  = delta_now                                                 %>% 
               dplyr::select(-c(year,case,desc))                         %>% 
               group_by(site,treatment,dbh)                              %>% 
               summarize_all(mean,na.rm=TRUE)
    
    delta_szdist_mean = rbind(delta_szdist_mean,mean_sz)
    
    sd_sz  = delta_now                                                 %>% 
             dplyr::select(-c(year,case,desc))                         %>% 
             group_by(site,treatment,dbh)                              %>% 
             summarize_all(sd,na.rm=TRUE)
    delta_szdist_sd = rbind(delta_szdist_sd,sd_sz)
    
    se_sz  = delta_now                          %>% 
             select(-c(year,case,desc))         %>% 
             group_by(site,treatment,dbh)       %>% 
             summarize_all(funs(se=sd(.,na.rm=TRUE)/sqrt(sum(!is.na(.)))))
    delta_szdist_se = rbind(delta_szdist_se,se_sz)
    
     
}




```





```{r PlotDeltaSizeDistribution}

plot_df = delta_sz
plot_df$dbh = factor(plot_df$dbh,levels=unique(plot_df$dbh))

for(d in sequence(n_delta)){
  f_vnam = delta_szvar[d]
  f_desc = sz_desc[d]
  plot = ggplot(plot_df,aes_string(x = "dbh",y=f_vnam,
                   #ymin=plot_df[[f_vnam]]-delta_szdist_sd[[f_vnam]],
                   #ymax=plot_df[[f_vnam]]+delta_szdist_sd[[f_vnam]],
                   colour="treatment")) +
       facet_wrap(.~site)+#,scales="free")+
       geom_boxplot(outlier.shape = NA) +
       geom_hline(yintercept = 0, color="black",linetype=2)+
       scale_x_discrete(labels=dbh_labs[4:13]) +
       scale_colour_manual(values=c("Burn-Cool" = "#836B43",
                                    "Burn-Hot" = "#D68D18",
                                    "Thin" = "#A0AE6A")) +
       ylab(paste0("Relative change in ", f_desc," (%)")) +
       xlab("") +
       theme_grey( base_size = gg_ptsz, base_family = "Helvetica",base_line_size = 0.5,base_rect_size =0.5) +
       theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , angle  = 90
                                              , hjust  = 1
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+
  
  
  for (d in sequence(ndevice)){
    f_output = paste0(f_vnam,"_delta-szdist.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = plot
                    , device   = gg_device[d]
                    , path     = size_path
                    , width    = gg_widthn*0.8
                    , height   = gg_height*0.7
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
   }
       

  
}


```




```{r DeltaFuelProcessing}

hlm1d = data.table::fread(file.path(main_path,model_file_name[1]))
fuel  = data.table::fread(file.path(main_path,model_file_name[5]))

fuel$fuel = factor(fuel$fuel,levels=unique(fuel$fuel))

fuel_notrunk = fuel                            %>% 
               filter(fuel!=4)                 %>% 
               group_by(case,desc,time)        %>% 
               select(-fuel)                   %>% 
               summarize_all(sum,na.rm=TRUE)   %>% 
               ungroup()                       %>% 
               rename(fates_fuel_notrunk = 
                      fates_fuel_amount)
fuel_trunk   = fuel                      %>% 
               filter(fuel==4)           %>% 
               select(-fuel)             %>% 
               rename(fates_fuel_trunk =
                      fates_fuel_amount)
fuel_cwd     = fuel                          %>% 
               filter(fuel %in% c(1,2,3))    %>% 
               select(-fuel)                 %>% 
               group_by(case,desc,time)      %>% 
               summarize_all(sum,na.rm=TRUE) %>%
               ungroup()                     %>% 
               rename(fates_fuel_cwd = 
                      fates_fuel_amount)
fuel_litter  = fuel                          %>% 
               filter(fuel ==5)              %>% 
               select(-fuel)                 %>%
               rename(fates_fuel_litter = 
                      fates_fuel_amount)

canopy_fuel  = hlm1d                              %>% 
               select(case,
                      time,
                      desc,
                      fates_canopy_fuel_amount,
                      fates_canopy_fuel_bulkd) 

fuel_df  = fuel_notrunk                          %>% 
           left_join(fuel_trunk,
                     by=c("case","desc","time")) %>% 
           left_join(fuel_cwd,
                     by=c("case","desc","time")) %>% 
           left_join(fuel_litter,
                     by=c("case","desc","time")) %>% 
           left_join(canopy_fuel,
                     by=c("case","desc","time"))

ctrl_fuel = fuel_df %>% filter(case %in% c(1,5,9))
ctrl_fuel = ctrl_fuel                      %>% 
            group_by(case,desc)            %>% 
            slice(rep(seq_len(n()),times = nsites)) %>% ungroup()


fuel_vars = c("fates_fuel_notrunk",
              "fates_fuel_trunk",
              "fates_fuel_cwd",
              "fates_fuel_litter",
              "fates_canopy_fuel_amount",
              "fates_canopy_fuel_bulkd")
fuel_desc = c("non-trunk fuel load",
              "trunk fuel load",
              "coarse woody debris",
              "dead fine fuels",
              "canopy fuel load",
              "canopy bulk density")

n_fuel = length(fuel_vars)


ctrl_fuel =  ctrl_fuel                    %>% 
             select(all_of(fuel_vars))     %>% 
             rename_at(vars(fates_fuel_notrunk:fates_canopy_fuel_bulkd),rename_fun)

treat_fuel = fuel_df                                 %>% 
             filter(!case%in% c(1,5,9))             
  
delta_fuel = cbind(treat_fuel,ctrl_fuel)

delta_fuel = delta_fuel                    %>% 
             mutate(site=site_grab(desc))
delta_fuel$treatment = unlist(lapply(delta_fuel$desc,treatment_grab))


for(v in sequence(n_fuel)){
  var_now = fuel_vars[v]
  delta_fuel[[var_now]] = delta_pct_fun(delta_fuel,var_now,1,0)
}

delta_fuel =  delta_fuel           %>% 
              mutate_at(vars(fates_fuel_notrunk:fates_canopy_fuel_bulkd),
                        zero_to_na)
       
deltafuel_mean   = NULL
deltafuel_sd     = NULL
deltafuel_se     = NULL

for(n in treated_case){
  delta_now = delta_fuel %>% filter(case==n)
 
  mean_fuel  = delta_now                                            %>% 
              select(-c(time,case,desc))                            %>% 
              group_by(site,treatment)                              %>% 
              summarize_all(mean,na.rm=TRUE)
    
  deltafuel_mean = rbind(deltafuel_mean,mean_fuel)
    
  sd_fuel  = delta_now                                             %>% 
             select(-c(time,case,desc))                            %>% 
             group_by(site,treatment)                              %>% 
             summarize_all(sd,na.rm=TRUE)
  deltafuel_sd = rbind(deltafuel_sd,sd_fuel)
  
  se_fuel  = delta_now                                             %>% 
             select(-c(time,case,desc))                            %>% 
             group_by(site,treatment)                              %>% 
             summarize_all(funs(se=sd(.,na.rm=TRUE)/sqrt(sum(!is.na(.)))))
  deltafuel_se = rbind(deltafuel_se,se_fuel)
    
     
}


```





```{r PlotDeltaFuel, echo=FALSE}


plot_df = deltafuel_mean

for(d in sequence(n_fuel)){
  f_vnam = fuel_vars[d]
  f_desc = fuel_desc[d]
  plot = ggplot(plot_df,aes_string(x = "site",y=f_vnam,
                   ymin=plot_df[[f_vnam]]-deltafuel_sd[[f_vnam]],
                   ymax=plot_df[[f_vnam]]+deltafuel_sd[[f_vnam]],
                   colour="treatment")) +
       geom_point(size=2) +
       geom_errorbar(width=0)+
       geom_hline(yintercept = 0, color="black",linetype=2)+
       coord_flip() +
       scale_colour_manual(values=c("Burn-Cool" = "#836B43",
                                    "Burn-Hot" = "#D68D18",
                                    "Thin" = "#A0AE6A")) +
       ylab(paste0("Relative change in ", f_desc," (%)")) +
       xlab("") +
       theme_grey( base_size = gg_ptsz, base_family = "Helvetica",base_line_size = 0.5,base_rect_size =0.5) +
       theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+
  
  
  for (d in sequence(ndevice)){
    f_output = paste0(f_vnam,"_delta.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = plot
                    , device   = gg_device[d]
                    , path     = mean_path
                    , width    = gg_widthn*0.5
                    , height   = gg_height*0.4
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
   }
       

  
}





```




```{r CombineObsFiles}

all_obs_paths = c("ba_path","nplant_path","ctrl_growth_path","delta_growth_path","mort_path","sz_path","fuel_path",
                  "diff_ba_path","diff_sd_path","diff_szdist_path","diff_fuel_path")
obs_file_name = c("ba-obs.csv","nplant-obs.csv","ctrl-ddbh-obs.csv","ddbh-obs.csv","mort-obs.csv","szdist-obs.csv","fuel-obs.csv", "prepost-ba-obs.csv","prepost-sd-obs.csv","prepost-szdist-obs.csv","prepost-fuel-obs.csv")
n_path = length(all_obs_paths)
for(p in sequence(n_path)){
  p_now = get(all_obs_paths[p])
  n_file = length(p_now)
  f_now = obs_file_name[p]
  tab = NULL
  for(f in sequence(n_file)){
     path_now = p_now[f]
     site_now = stringr::str_extract(path_now,"(?<=_)[^_]+(?=\\.csv$)")
     df_now = data.table::fread(path_now)
     df_now$site = site_now
     tab = rbind(tab,df_now,fill=TRUE)
  }
  data.table::fwrite(tab,file=file.path(obs_path,f_now))
}




```





```{r RelativeChangeinStructureBenchmark}

## benchmark baseline simulation

model_ctrl_struc = overall_na                            %>% 
                   select(case,desc,
                          fates_basalarea,
                          fates_nplant)                  %>% 
                   filter(case %in% c(1,5,9)) 
model_ctrl_struc_mean = model_ctrl_struc                 %>% 
                   group_by(case,desc)                   %>% 
                   summarize_all(mean,na.rm=TRUE)        %>% 
                   ungroup()
model_ctrl_struc_se = model_ctrl_struc                   %>% 
                   group_by(case,desc)                   %>% 
                   summarize_all(funs(se=sd(.,na.rm=TRUE)/sqrt(sum(!is.na(.)))))        %>% 
                   ungroup()                            
model_ctrl_struc = model_ctrl_struc_mean %>% left_join(model_ctrl_struc_se,by=c("case","desc"))
model_ctrl_struc = model_ctrl_struc                 %>% 
                      mutate(site=site_grab(desc))
model_ctrl_struc$treatment = unlist(lapply(model_ctrl_struc$desc,treatment_grab))
model_ctrl_struc = model_ctrl_struc                 %>% 
                      select(-c(case,desc))               %>% 
                      mutate(type="Model")
obs_ba = fread(file.path(obs_path,"ba-obs.csv"))
obs_nplant = fread(file.path(obs_path,"nplant-obs.csv"))
obs_ctrl_ba = obs_ba                              %>% 
              select(Treatment,site,Avg, SE_Avg)  %>% 
              rename(treatment = Treatment,
                     fates_basalarea = Avg,
                     fates_basalarea_se = SE_Avg) %>% 
              filter(treatment == "None")
obs_ctrl_nplant = obs_nplant                             %>% 
                  select(Treatment, site, Avg, SE_Avg)   %>% 
                  rename(treatment = Treatment,
                         fates_nplant = Avg,
                         fates_nplant_se = SE_Avg)       %>% 
                  filter(treatment == "None")
obs_ctrl_struc = obs_ctrl_ba %>% left_join(obs_ctrl_nplant,by=c("site","treatment"))
obs_ctrl_struc$type = "Observation"
model_ctrl_struc = rbind(model_ctrl_struc, obs_ctrl_struc) 

plot_vars = c("fates_basalarea","fates_nplant")
plot_desc = c("Basal area", "Stem density")
n_plot = length(plot_vars)
gg_struc = list()
for(n in sequence(n_plot)){
  var_now = plot_vars[n]
  desc_now = plot_desc[n]
  se_var = paste0(var_now,"_se")
  max_y <- max(model_ctrl_struc[[var_now]]) + max(model_ctrl_struc[[se_var]]) + 5
  gg_now <- ggplot(model_ctrl_struc,aes_string(x="site",y=var_now,fill="type")) 
  gg_now <- gg_now + geom_bar(position=position_dodge2(),stat="identity",width=0.6)
  if(n==1){unit <- quote(m^2~ha-1)
  gg_now <- gg_now + geom_errorbar(aes(ymin=fates_basalarea-fates_basalarea_se,
                         ymax=fates_basalarea+fates_basalarea_se),
                     width=0.2,
                     position=position_dodge(0.6),stat="identity")} 
  if(n==2){unit <- quote(plants~ha^-1)
  gg_now <- gg_now + geom_errorbar(aes(ymin=fates_nplant - fates_nplant_se,
                         ymax=fates_nplant + fates_nplant_se),
                     width=0.2,
                     position=position_dodge(0.6),stat="identity")}
  gg_now = gg_now + scale_fill_manual(values=c("grey","grey50"))
  gg_now = gg_now + coord_cartesian(ylim=c(0,max_y))
  gg_now = gg_now + ylab(bquote(.(desc_now)~"("~.(unit)~")"))
  gg_now = gg_now + xlab(" ") 
  gg_now = gg_now + theme_grey( base_size = gg_ptsz, base_family = "Helvetica",
                                base_line_size = 0.5,base_rect_size =0.5) 
  gg_now = gg_now + theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

for (d in sequence(ndevice)){
    f_output = paste0(var_now,"ctrl_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = gg_now
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.4
                    , height   = gg_height*0.6
                    , units    = gg_units
                    , dpi      = gg_depth
    )
    }
  gg_struc[[n]] = gg_now
}

gg_patch = wrap_plots(gg_struc[[1]], gg_struc[[2]]) +
  plot_layout(guides="collect",ncol=2) & theme(legend.position="bottom")

for (d in sequence(ndevice)){
    f_output = paste0("ctrl-struc_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = gg_patch
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.8
                    , height   = gg_height*0.6
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
 }


model_struc = delta_mean %>% select(site, treatment, fates_nplant, fates_basalarea)
model_struc_se   = delta_se                        %>% 
                   select(site,treatment, fates_nplant_se,fates_basalarea_se) #%>% 
                   #rename_if(is.numeric,rename_sd)
model_struc = model_struc %>% left_join(model_struc_se, by=c("site","treatment"))


model_struc = model_struc                                           %>% 
              mutate(type = case_when(treatment=="Burn-Cool" ~ "Model-BurnCool",
                                      treatment=="Burn-Hot" ~ "Model-BurnHot",
                                      treatment=="Thin" ~ "Model-Thin"),
                     treatment = ifelse(treatment=="Thin", treatment, "Burn")
                                       )


obs_ba_avg = obs_ba                       %>% 
             select(Treatment,site,
                    Avg_pct_diff,
                    SE_Avg_pct_diff
                   )
obs_ba_final = obs_ba                 %>% 
               select(Treatment,site,
                      Fnl_pct_diff,
                      SE_Fnl_pct_diff)
obs_ba_avg  = obs_ba_avg                     %>% 
              rename(treatment = Treatment,
                fates_basalarea = Avg_pct_diff,
                fates_basalarea_se = SE_Avg_pct_diff) %>% 
              filter(!treatment %in% c("Burn+Thin","None"))      %>% 
              mutate(type="Observation")

obs_ba_avg = rbind(obs_ba_avg, burn_rep)

              
          
obs_nplant_avg = obs_nplant              %>% 
                 select(Treatment,
                        site,
                        Avg_pct_diff,
                        SE_Avg_pct_diff)
obs_nplant_avg = obs_nplant_avg                   %>% 
             rename(treatment = Treatment,
                    fates_nplant = Avg_pct_diff,
                    fates_nplant_se = SE_Avg_pct_diff) %>% 
             filter(!treatment %in% c("Burn+Thin","None"))  

obs_nplant_avg = rbind(obs_nplant_avg, burn_rep)

obs_struc = obs_nplant_avg %>% left_join(obs_ba_avg,by=c("site","treatment"))
model_struc = rbind(model_struc,obs_struc)



delta_ba_plot  = ggplot(model_struc,aes(x=site,y=fates_basalarea,
                   fill=type)) +
       facet_wrap(.~treatment) +              
       geom_bar(position=position_dodge(),stat="identity",width=0.6) +
       geom_errorbar(aes(ymin=fates_basalarea - fates_basalarea_se,
                         ymax=fates_basalarea + fates_basalarea_se),
                     width=0.2,
                     position=position_dodge(0.6))+
       scale_fill_manual(values=c("Model-BurnCool" = "#836B43",
                                  "Model-BurnHot" = "#D68D18",
                                  "Model-Thin" = "#A0AE6A",
                                  "Observation" = "#437683"))+
       ylab(paste0("Relative change in basal area "," (%)")) +
       xlab("") +
       theme_grey( base_size = gg_ptsz, base_family = "Helvetica",base_line_size = 0.5,base_rect_size =0.5) +
       theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm")
                                              , angle  = 90
                                              , hjust  = 1)#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

 for (d in sequence(ndevice)){
    f_output = paste0("delta_ba_benchmark_SE.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = delta_ba_plot
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.6
                    , height   = gg_height*0.75
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
   }


delta_stem_plot  = ggplot(model_struc,aes(x=site,y=fates_nplant,
                   fill=type)) +
       facet_wrap(.~treatment) +              
       geom_bar(position=position_dodge(),stat="identity",width=0.6) +
       geom_errorbar(aes(ymin=fates_nplant - fates_nplant_se,
                         ymax=fates_nplant + fates_nplant_se),
                     width=0.2,
                     position=position_dodge(0.6))+
       scale_fill_manual(values=c("Model-BurnCool" = "#836B43",
                                  "Model-BurnHot" = "#D68D18",
                                  "Model-Thin" = "#A0AE6A",
                                  "Observation" = "#437683"))+
       ylab(paste0("Relative change in stem density "," (%)")) +
       xlab("") +
       theme_grey( base_size = gg_ptsz, base_family = "Helvetica",base_line_size = 0.5,base_rect_size =0.5) +
       theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm")
                                              , angle  = 90
                                              , hjust  = 1)#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

for (d in sequence(ndevice)){
    f_output = paste0("delta_stem_benchmark_SE.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = delta_stem_plot
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.6
                    , height   = gg_height*0.75
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
   }


```





```{r PrePostStructureBenchmark}
## Blodgett
mod_prethin_struc_bldgt = bypft                       %>% 
                      filter(year == 2001 &
                             case == 2)               %>% 
                      select(case,time,desc,
                             fates_basalarea,
                             fates_nplant)            %>% 
                      group_by(case,desc,time)        %>% 
                      summarize_all(sum,na.rm=TRUE)   %>% 
                      ungroup()                       %>% 
                      group_by(case,desc)             %>% 
                      select(-time)                   %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()

mod_prerx_struc_bldgt = bypft                         %>% 
                      filter(year == 2001 &
                             month %in% c(1:4) &
                             case %in% c(3:4))       %>% 
                      select(case,time,desc,
                             fates_basalarea,
                             fates_nplant)            %>% 
                      group_by(case,desc,time)        %>% 
                      summarize_all(sum,na.rm=TRUE)   %>% 
                      ungroup()                       %>%
                      group_by(case,desc)             %>% 
                      select(-time)                   %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()

mod_postthin_struc_bldgt = bypft                      %>% 
                      filter(year != 2001 &
                             case == 2)               %>% 
                      select(case,time,desc,
                             fates_basalarea,
                             fates_nplant)            %>% 
                      group_by(case,desc,time)        %>% 
                      summarize_all(sum,na.rm=TRUE)   %>% 
                      ungroup()                       %>% 
                      group_by(case,desc)             %>% 
                      select(-time)                   %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       %>% 
                      rename_at(vars(fates_basalarea:fates_nplant),
                             post_rename)
mod_postrx_struc_bldgt = bypft                         %>% 
                      filter(year != 2001 &
                             case %in% c(3:4))       %>% 
                      select(case,time,desc,
                             fates_basalarea,
                             fates_nplant)            %>% 
                      group_by(case,desc,time)        %>% 
                      summarize_all(sum,na.rm=TRUE)   %>% 
                      ungroup()                       %>% 
                      group_by(case,desc)             %>% 
                      select(-time)                   %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       %>% 
                      rename_at(vars(fates_basalarea:fates_nplant),
                                post_rename)

## STEF

mod_prethin_struc_stef = bypft                       %>% 
                      filter(year == 2011 &
                             month == 1 &
                             case == 6)               %>% 
                      select(case,time,desc,
                             fates_basalarea,
                             fates_nplant)            %>% 
                      group_by(case,desc,time)        %>% 
                      summarize_all(sum,na.rm=TRUE)   %>% 
                      ungroup()                       %>% 
                      group_by(case,desc)             %>% 
                      select(-time)                   %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       

mod_prerx_struc_stef = bypft                         %>% 
                      filter(year == 2011 &
                             month %in% c(1:4) &
                             case %in% c(7:8))       %>% 
                      select(case,time,desc,
                             fates_basalarea,
                             fates_nplant)            %>% 
                      group_by(case,desc,time)        %>% 
                      summarize_all(sum,na.rm=TRUE)   %>% 
                      ungroup()                       %>%
                      group_by(case,desc)             %>% 
                      select(-time)                   %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()

mod_postthin_struc_stef = bypft                      %>% 
                      filter(year != 2011 &
                             case == 6)               %>% 
                      select(case,time,desc,
                             fates_basalarea,
                             fates_nplant)            %>% 
                      group_by(case,desc,time)        %>% 
                      summarize_all(sum,na.rm=TRUE)   %>% 
                      ungroup()                       %>% 
                      group_by(case,desc)             %>% 
                      select(-time)                   %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       %>% 
                      rename_at(vars(fates_basalarea:fates_nplant),
                             post_rename)

mod_postrx_struc_stef = bypft                         %>% 
                      filter(year != 2011 &
                             case %in% c(7:8))       %>% 
                      select(case,time,desc,
                             fates_basalarea,
                             fates_nplant)            %>% 
                      group_by(case,desc,time)        %>% 
                      summarize_all(sum,na.rm=TRUE)   %>% 
                      ungroup()                       %>% 
                      group_by(case,desc)             %>% 
                      select(-time)                   %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       %>% 
                      rename_at(vars(fates_basalarea:fates_nplant),
                                post_rename)

## Teakettle

mod_prethin_struc_tea = bypft                       %>% 
                      filter(year == 2001 &
                             month == 1 &
                             case == 10)               %>% 
                      select(case,time,desc,
                             fates_basalarea,
                             fates_nplant)            %>% 
                      group_by(case,desc,time)        %>% 
                      summarize_all(sum,na.rm=TRUE)   %>% 
                      ungroup()                       %>% 
                      group_by(case,desc)             %>% 
                      select(-time)                   %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       

mod_prerx_struc_tea = bypft                         %>% 
                      filter(year == 2001 &
                             month %in% c(1:4) &
                             case %in% c(11:12))       %>% 
                      select(case,time,desc,
                             fates_basalarea,
                             fates_nplant)            %>% 
                      group_by(case,desc,time)        %>% 
                      summarize_all(sum,na.rm=TRUE)   %>% 
                      ungroup()                       %>%
                      group_by(case,desc)             %>% 
                      select(-time)                   %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()

mod_postthin_struc_tea = bypft                      %>% 
                      filter(year != 2001 &
                             case == 10)               %>% 
                      select(case,time,desc,
                             fates_basalarea,
                             fates_nplant)            %>% 
                      group_by(case,desc,time)        %>% 
                      summarize_all(sum,na.rm=TRUE)   %>% 
                      ungroup()                       %>% 
                      group_by(case,desc)             %>% 
                      select(-time)                   %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       %>% 
                      rename_at(vars(fates_basalarea:fates_nplant),
                             post_rename)

mod_postrx_struc_tea = bypft                         %>% 
                      filter(year != 2001 &
                             case %in% c(11:12))       %>% 
                      select(case,time,desc,
                             fates_basalarea,
                             fates_nplant)            %>% 
                      group_by(case,desc,time)        %>% 
                      summarize_all(sum,na.rm=TRUE)   %>% 
                      ungroup()                       %>% 
                      group_by(case,desc)             %>% 
                      select(-time)                   %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       %>% 
                      rename_at(vars(fates_basalarea:fates_nplant),
                                post_rename)

mod_pre_struc = rbind(mod_prethin_struc_bldgt,mod_prerx_struc_bldgt,
                      mod_prethin_struc_stef,mod_prerx_struc_stef,
                      mod_prethin_struc_tea,mod_prerx_struc_tea)
mod_post_struc = rbind(mod_postthin_struc_bldgt,mod_postrx_struc_bldgt,
                       mod_postthin_struc_stef, mod_postrx_struc_stef,
                       mod_postthin_struc_tea, mod_postrx_struc_tea)

mod_prpo_struc = mod_pre_struc %>% left_join(mod_post_struc,by=c("case","desc"))

prpo_vars = names(mod_prpo_struc)[grepl("fates_",names(mod_prpo_struc))]
n_var = length(prpo_vars)
for(n in sequence(n_var)){
  var_now = prpo_vars[n]
  mod_prpo_struc[[var_now]] = prepost_pct_diff(mod_prpo_struc,var_now)
  
}
mod_prpo_struc = mod_prpo_struc %>% mutate(site=site_grab(desc))
mod_prpo_struc$treatment = unlist(lapply(mod_prpo_struc$desc,treatment_grab))
mod_prpo_struc$fates_basalarea_se = NA
mod_prpo_struc$fates_nplant_se = NA

mod_prpo_struc = mod_prpo_struc                                                        %>% 
                 mutate(type = case_when(treatment=="Burn-Cool" ~ "Model-BurnCool",
                                         treatment=="Burn-Hot" ~ "Model-BurnHot",
                                         treatment=="Thin" ~ "Model-Thin"),
                        treatment = ifelse(treatment=="Thin", treatment, "Burn"))

mod_prpo_struc = mod_prpo_struc %>% select(-c(case,desc,post_basalarea,post_nplant))
 
obs_prpo_ba = fread(file.path(obs_path,"prepost-ba-obs.csv"))


obs_prpo_ba = obs_prpo_ba                      %>% 
              filter(DBH_timeframe == "Post" &
                     Treatment != "Burn+Thin")  %>% 
              select(site,Treatment,
                     PrePost_pct_diff,
                     SE_PrePost_pct_diff)      %>% 
              rename(treatment = Treatment,
                     fates_basalarea = PrePost_pct_diff,
                     fates_basalarea_se = SE_PrePost_pct_diff)

obs_prpo_sd = fread(file.path(obs_path,"prepost-sd-obs.csv"))
obs_prpo_sd = obs_prpo_sd                      %>% 
              filter(DBH_timeframe == "Post" &
                     Treatment != "Burn+Thin")  %>% 
              select(site,Treatment,
                     PrePost_pct_diff,
                     SE_PrePost_pct_diff)      %>% 
              rename(treatment = Treatment,
                     fates_nplant = PrePost_pct_diff,
                     fates_nplant_se = SE_PrePost_pct_diff)
obs_prpo_struc = obs_prpo_ba %>% left_join(obs_prpo_sd,by=c("site","treatment"))
obs_prpo_struc = obs_prpo_struc %>% mutate(type = "Observation")

mod_prpo_struc = rbind(mod_prpo_struc,obs_prpo_struc)


plot_desc = c("basal area", "stem density")
n_plot = length(prpo_vars)
gg_prpo_struc = list()

for(n in sequence(n_plot)){
  var_now = prpo_vars[n]
  desc_now = plot_desc[n]
  se_var = paste0(var_now,"_se")
  max_y <- max(mod_prpo_struc[[var_now]]) + max(mod_prpo_struc[[se_var]],na.rm=TRUE) + 5
  min_y <- min(mod_prpo_struc[[var_now]]) + min(mod_prpo_struc[[se_var]],na.rm=TRUE) - 10
  gg_now <- ggplot(mod_prpo_struc,aes_string(x="treatment",y=var_now,fill="type")) 
  gg_now <- gg_now + geom_bar(position=position_dodge2(),stat="identity",width=0.6)
  if(n==1){
    gg_now <- gg_now + geom_errorbar(aes(ymin=fates_basalarea-fates_basalarea_se,
                         ymax=fates_basalarea+fates_basalarea_se),
                     width=0.2,
                     position=position_dodge(0.6),stat="identity")
  }else if(n==2){
    gg_now <- gg_now + geom_errorbar(aes(ymin=fates_nplant - fates_nplant_se,
                         ymax=fates_nplant + fates_nplant_se),
                     width=0.2,
                     position=position_dodge(0.6),stat="identity")}
  gg_now = gg_now + facet_wrap(.~site,ncol=3)
  gg_now = gg_now + scale_fill_manual(values=c("Model-BurnCool" = "#836B43",
                                  "Model-BurnHot" = "#D68D18",
                                  "Model-Thin" = "#A0AE6A",
                                  "Observation" = "#437683"))
  gg_now = gg_now + coord_cartesian(ylim=c(min_y,max_y))
  gg_now = gg_now + ylab(paste("Pre-post change in", desc_now, "( % )",sep=" "))
  gg_now = gg_now + xlab(" ") 
  gg_now = gg_now + theme_grey( base_size = gg_ptsz, base_family = "Helvetica",
                                base_line_size = 0.5,base_rect_size =0.5) 
  gg_now = gg_now + theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm")
                                              , angle = 90
                                              , hjust = 1)#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

for (d in sequence(ndevice)){
    f_output = paste0(var_now,"prepost_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = gg_now
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.5
                    , height   = gg_height*0.7
                    , units    = gg_units
                    , dpi      = gg_depth
    )
    }
  gg_prpo_struc[[n]] = gg_now
}

gg_patch = wrap_plots(gg_prpo_struc[[1]], gg_prpo_struc[[2]]) +
  plot_layout(guides="collect",ncol=2) & theme(legend.position="bottom")

for (d in sequence(ndevice)){
    f_output = paste0("prpo-struc_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = gg_patch
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.6
                    , height   = gg_height*0.7
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
 }




```





```{r SizeDistributionBenchmark}

## benchmark baseline simulations first
ctrl_sz_mod = sz_model                               %>% 
              filter(case %in% c(1,5,9))             %>% 
              select(case,desc,dbh,fates_nplant)     %>% 
              group_by(case,desc,dbh)                %>% 
              summarize_all(mean,na.rm=TRUE)         %>% 
              ungroup()
ctrl_sz_mod_se = sz_model                            %>% 
              filter(case %in% c(1,5,9))             %>% 
              select(case,desc,dbh,fates_nplant)     %>% 
              group_by(case,desc,dbh)                %>% 
              summarize_all(funs(fates_nplant_se=sd(.,na.rm=TRUE)/sqrt(sum(!is.na(.))))) %>% 
              ungroup()
ctrl_sz_mod = ctrl_sz_mod %>% left_join(ctrl_sz_mod_se,by=c("case","desc","dbh"))

ctrl_sz_mod$treatment = unlist(lapply(ctrl_sz_mod$desc,treatment_grab))
ctrl_sz_mod = ctrl_sz_mod                       %>% 
              mutate(site = site_grab(desc),
                     type = "Model")            %>% 
              select(site,treatment,type,dbh,
                     fates_nplant,
                     fates_nplant_se)
obs_szdist = fread(file.path(obs_path,"szdist-obs.csv"))
obs_szdist = obs_szdist                          %>% 
             mutate(dbh = case_when(Size_class<=20 ~ 4,
                                    Size_class<=30 ~ 5,
                                    Size_class<=40 ~ 6,
                                    Size_class<=50 ~ 7,
                                    Size_class<=60 ~ 8,
                                    Size_class<=70 ~ 9,
                                    Size_class<=80 ~ 10,
                                    Size_class<=90 ~ 11,
                                    Size_class<=100 ~ 12,
                                    Size_class>100 ~ 13))
ctrl_sz_obs = obs_szdist                             %>% 
              filter(Treatment=="None")              %>% 
              select(Treatment,dbh,
                     site,Avg,SE_Avg)                %>% 
              rename(treatment = Treatment,
                     fates_nplant = Avg,
                     fates_nplant_se = SE_Avg)      %>% 
              mutate(type="Observation")
ctrl_sz_mod = rbind(ctrl_sz_mod,ctrl_sz_obs) 
plot_df = ctrl_sz_mod
plot_df$dbh = factor(plot_df$dbh,levels=unique(plot_df$dbh))

gg_now = ggplot(plot_df,aes(x=dbh,y=fates_nplant,fill=type)) 
gg_now = gg_now + facet_wrap(.~site)
gg_now = gg_now + geom_bar(position=position_dodge(),stat="identity",width=0.6) 
gg_now = gg_now + geom_errorbar(aes(ymin=fates_nplant-fates_nplant_se,
                         ymax=fates_nplant+fates_nplant_se),
                     width=0.2,
                     position=position_dodge(0.6))
  
gg_now = gg_now + scale_fill_manual(values=c("grey","grey50"))
gg_now = gg_now + scale_x_discrete(labels=dbh_labs[4:13])
gg_now = gg_now + ylab(expression("Stem density by sze class"~"( Plants"~ha^-1~")"))
gg_now = gg_now + xlab(" ") 
gg_now = gg_now + theme_grey( base_size = gg_ptsz, base_family = "Helvetica",
                                base_line_size = 0.5,base_rect_size =0.5) 
gg_now = gg_now + theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm")
                                              , angle = 90
                                              , hjust = 1)#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

for (d in sequence(ndevice)){
    f_output = paste0("szdist_ctrl_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = gg_now
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.8
                    , height   = gg_height*0.75
                    , units    = gg_units
                    , dpi      = gg_depth
    )
    }


## benchmark delta size distribution

mod_szdist = delta_szdist_mean %>% select(site,treatment,dbh,fates_nplant)
mod_szdist_se = delta_szdist_se                            %>% 
                select(site,treatment,dbh,fates_nplant_se) 

mod_szdist = mod_szdist %>% left_join(mod_szdist_se, by=c("site","treatment","dbh"))

mod_szdist = mod_szdist                      %>% 
             mutate(type = case_when(treatment=="Burn-Cool" ~ "Model-BurnCool",
                                      treatment=="Burn-Hot" ~ "Model-BurnHot",
                                      treatment=="Thin" ~ "Model-Thin"),
                    treatment = ifelse(treatment=="Thin", treatment, "Burn"))


obs_szdist_avg = obs_szdist                       %>% 
                 select(Treatment,site,
                    dbh,
                    Avg_pct_diff,
                    SE_Avg_pct_diff
                   )
obs_szdist_final = obs_szdist                 %>% 
                   select(Treatment,site,
                      dbh,
                      Fnl,
                      SE_Fnl)
obs_szdist_avg  = obs_szdist_avg                     %>% 
                  rename(treatment = Treatment,
                         fates_nplant = Avg_pct_diff,
                         fates_nplant_se    = SE_Avg_pct_diff) %>% 
              filter(!treatment %in% c("Burn+Thin","None"))    %>% 
              mutate(type="Observation")

mod_szdist = rbind(mod_szdist,obs_szdist_avg)

plot_df = mod_szdist
plot_df$dbh = factor(plot_df$dbh,levels=unique(plot_df$dbh))

delta_szdist_plot  = ggplot(plot_df,aes(x=dbh,y=fates_nplant,
                   fill=type)) +
       facet_wrap(treatment~site) +              
       geom_bar(position=position_dodge(),stat="identity",width=0.8) +
       geom_errorbar(aes(ymin=fates_nplant - fates_nplant_se,
                         ymax=fates_nplant + fates_nplant_se),
                     width=0.2,
                     position=position_dodge(0.8))+
       scale_x_discrete(labels=dbh_labs[4:13]) +
       scale_fill_manual(values=c("Model-BurnCool" = "#836B43",
                                  "Model-BurnHot" = "#D68D18",
                                  "Model-Thin" = "#A0AE6A",
                                  "Observation" = "#437683"))+
       ylab(paste0("Relative change in stem density by size class "," (%)")) +
       xlab("") +
       theme_grey( base_size = gg_ptsz, base_family = "Helvetica",base_line_size = 0.5,base_rect_size =0.5) +
       theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , angle  = 90
                                              , hjust  = 1
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

 for (d in sequence(ndevice)){
    f_output = paste0("delta_szdist_benchmark_SE.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = delta_szdist_plot
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.7
                    , height   = gg_height*0.8
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
   }




```





```{r PrePostSizeStructureBenchmark}

## Blodgett
mod_prethin_szdist_bldgt = bydbh                      %>%
                      mutate(year = year(time))       %>% 
                      filter(year == 2001 &
                             case == 2 &
                             dbh %in% c(4:13))        %>% 
                      select(case,desc,
                             dbh,
                             fates_nplant)            %>% 
                      group_by(case,desc,dbh)         %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       


mod_prerx_szdist_bldgt = bydbh                       %>% 
                      mutate(year = year(time),
                             month = month(time))    %>% 
                      filter(year == 2001 &
                             month %in% c(1:4) &
                             case %in% c(3:4) &
                             dbh %in% c(4:13))        %>% 
                      select(case,desc,dbh,
                             fates_nplant)            %>% 
                      group_by(case,desc,dbh)         %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       

mod_postthin_szdist_bldgt = bydbh                     %>% 
                      mutate(year = year(time))       %>% 
                      filter(year != 2001 &
                             case == 2 &
                             dbh %in% c(4:13))        %>% 
                      select(case,desc,dbh,
                             fates_nplant)            %>% 
                      group_by(case,desc,dbh)         %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       %>%  
                      rename(post_nplant = fates_nplant)

mod_postrx_szdist_bldgt = bydbh                      %>%
                      mutate(year = year(time))      %>% 
                      filter(year != 2001 &
                             case %in% c(3:4) &
                             dbh %in% c(4:13))        %>% 
                      select(case,desc,dbh,
                             fates_nplant)            %>% 
                      group_by(case,desc,dbh)         %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       %>% 
                      rename(post_nplant = fates_nplant)

## STEF

mod_prethin_szdist_stef = bydbh                       %>% 
                      mutate(year = year(time),
                             month = month(time))     %>% 
                      filter(year == 2011 &
                             month == 1 &
                             case == 6 &
                             dbh %in% c(4:13))        %>% 
                      select(case,desc,dbh,
                             fates_nplant)            %>% 
                      group_by(case,desc,dbh)         %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       

mod_prerx_szdist_stef = bydbh                         %>%
                      mutate(year = year(time),
                             month = month(time))    %>% 
                      filter(year == 2011 &
                             month %in% c(1:4) &
                             case %in% c(7:8) &
                             dbh %in% c(4:13))        %>% 
                      select(case,desc,dbh,
                             fates_nplant)            %>% 
                      group_by(case,desc,dbh)         %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                      
                      

mod_postthin_szdist_stef = bydbh                      %>% 
                      mutate(year = year(time))       %>% 
                      filter(year != 2011 &
                             case == 6 &
                             dbh %in% c(4:13))        %>% 
                      select(case,desc,dbh,
                             fates_nplant)            %>% 
                      group_by(case,desc,dbh)         %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       %>% 
                      rename(post_nplant = fates_nplant)

mod_postrx_szdist_stef = bydbh                        %>% 
                      mutate(year = year(time))       %>% 
                      filter(year != 2011 &
                             case %in% c(7:8)&
                             dbh %in% c(4:13))        %>% 
                      select(case,desc,dbh,
                             fates_nplant)            %>% 
                      group_by(case,desc,dbh)         %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       %>% 
                      rename(post_nplant = fates_nplant)

## Teakettle

mod_prethin_szdist_tea = bydbh                       %>% 
                      mutate(year = year(time),
                             month = month(time))    %>% 
                      filter(year == 2001 &
                             month == 1 &
                             case == 10 &
                             dbh %in% c(4:13))       %>% 
                      select(case,desc,dbh,
                             fates_nplant)            %>% 
                      group_by(case,desc,dbh)         %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                      

mod_prerx_szdist_tea = bydbh                         %>% 
                      mutate(year = year(time),
                             month = month(time))    %>% 
                      filter(year == 2001 &
                             month %in% c(1:4) &
                             case %in% c(11:12) &
                             dbh %in% c(4:13))       %>% 
                      select(case,desc,dbh,
                             fates_nplant)            %>% 
                      group_by(case,desc,dbh)         %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       
                      

mod_postthin_szdist_tea = bydbh                      %>% 
                      mutate(year = year(time))      %>% 
                      filter(year != 2001 &
                             case == 10 &
                             dbh %in% c(4:13))        %>% 
                      select(case,desc,dbh,
                             fates_nplant)            %>% 
                      group_by(case,desc,dbh)         %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       %>% 
                      rename(post_nplant = fates_nplant)

mod_postrx_szdist_tea = bydbh                         %>% 
                      mutate(year = year(time))       %>% 
                      filter(year != 2001 &
                             case %in% c(11:12) &
                             dbh %in% c(4:13))        %>% 
                      select(case,desc,dbh,
                             fates_nplant)            %>% 
                      group_by(case,desc,dbh)         %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       %>% 
                      rename(post_nplant = fates_nplant)

mod_pre_szdist = rbind(mod_prethin_szdist_bldgt,mod_prerx_szdist_bldgt,
                      mod_prethin_szdist_stef,mod_prerx_szdist_stef,
                      mod_prethin_szdist_tea,mod_prerx_szdist_tea)
mod_post_szdist = rbind(mod_postthin_szdist_bldgt,mod_postrx_szdist_bldgt,
                       mod_postthin_szdist_stef, mod_postrx_szdist_stef,
                       mod_postthin_szdist_tea, mod_postrx_szdist_tea)

mod_prpo_szdist = mod_pre_szdist %>% left_join(mod_post_szdist,by=c("case","desc","dbh"))

prpo_vars = names(mod_prpo_szdist)[grepl("fates_",names(mod_prpo_szdist))]
n_var = length(prpo_vars)
for(n in sequence(n_var)){
  var_now = prpo_vars[n]
  mod_prpo_szdist[[var_now]] = prepost_pct_diff(mod_prpo_szdist,var_now)
  
}
mod_prpo_szdist = mod_prpo_szdist %>% mutate(site=site_grab(desc))
mod_prpo_szdist$treatment = unlist(lapply(mod_prpo_szdist$desc,treatment_grab))
mod_prpo_szdist$fates_nplant_se = NA


mod_prpo_szdist = mod_prpo_szdist                              %>% 
                  mutate(type = case_when(treatment=="Burn-Cool" ~ "Model-BurnCool",
                                      treatment=="Burn-Hot" ~ "Model-BurnHot",
                                      treatment=="Thin" ~ "Model-Thin"),
                         treatment = ifelse(treatment=="Thin", treatment, "Burn"))
mod_prpo_szdist = mod_prpo_szdist %>% select(-c(case,desc,post_nplant))
 
obs_prpo_szdist = fread(file.path(obs_path,"prepost-szdist-obs.csv"))


obs_prpo_szdist = obs_prpo_szdist               %>% 
              filter(DBH_timeframe == "Post" &
                     Treatment != "Burn+Thin")  %>% 
              select(site,Treatment,
                     Size_class,
                     PrePost_pct_diff,
                     SE_PrePost_pct_diff)       %>% 
              rename(treatment = Treatment,
                     dbh = Size_class,
                     fates_nplant = PrePost_pct_diff,
                     fates_nplant_se = SE_PrePost_pct_diff)



obs_prpo_szdist = obs_prpo_szdist                              %>% 
                  mutate(
                         type = "Observation",
                         dbh = case_when(dbh == 20 ~ 4,
                                         dbh == 30 ~ 5,
                                         dbh == 40 ~ 6,
                                         dbh == 50 ~ 7,
                                         dbh == 60 ~ 8,
                                         dbh == 70 ~ 9,
                                         dbh == 80 ~ 10,
                                         dbh == 90 ~ 11,
                                         dbh == 100 ~ 12,
                                         dbh > 100 ~ 13))

mod_prpo_szdist = rbind(mod_prpo_szdist,obs_prpo_szdist)

plot_df =mod_prpo_szdist
plot_df$dbh = factor(plot_df$dbh,levels=unique(plot_df$dbh))

  max_y = max(mod_prpo_szdist$fates_nplant,na.rm=TRUE) + max(mod_prpo_szdist$fates_nplant_se,na.rm=TRUE) 
  min_y = min(mod_prpo_szdist$fates_nplant,na.rm=TRUE) + min(mod_prpo_szdist$fates_nplant_se,na.rm=TRUE) 
  gg_now = ggplot(plot_df,aes(x=dbh,y=fates_nplant,fill=type)) 
  gg_now = gg_now + geom_bar(position=position_dodge2(),stat="identity",width=0.6)
  gg_now = gg_now + geom_errorbar(aes(ymin=fates_nplant - fates_nplant_se,
                         ymax=fates_nplant + fates_nplant_se),
                     width=0.2,
                     position=position_dodge(0.6),stat="identity")
  gg_now = gg_now + facet_wrap(treatment~site,ncol=3,scales="free_y")
  gg_now = gg_now + scale_fill_manual(values=c("Model-BurnCool" = "#836B43",
                                               "Model-BurnHot" = "#D68D18",
                                               "Model-Thin" = "#A0AE6A",
                                               "Observation" = "#437683"))
  #gg_now = gg_now + coord_cartesian(ylim=c(min_y,max_y))
  gg_now = gg_now + scale_x_discrete(labels=dbh_labs[4:13])
  gg_now = gg_now + ylab("Pre-post change in size distribution ( % )")
  gg_now = gg_now + xlab("Size class ( cm ) ") 
  gg_now = gg_now + theme_grey( base_size = gg_ptsz, base_family = "Helvetica",
                                base_line_size = 0.5,base_rect_size =0.5) 
  gg_now = gg_now + theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm")
                                              , angle = 90
                                              , hjust = 1)#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

for (d in sequence(ndevice)){
    f_output = paste0("szdist_prepost_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = gg_now
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.8
                    , height   = gg_height*0.8
                    , units    = gg_units
                    , dpi      = gg_depth
    )
    }





```






```{r GrowthBenchmark}

## benchmark baseline simulation of growth rate by PFT and size class

ddbh_szpf_mod = fread(file.path(main_path,model_file_name[6]))

ddbh_szpf_mod = ddbh_szpf_mod                  %>% 
                mutate(fates_ddbh=ifelse(fates_nplant==0, NA, fates_ddbh),
                       fates_nplant=ifelse(fates_nplant==0,NA,fates_nplant))
ddbh_szpf_mod = ddbh_szpf_mod                  %>% 
                mutate(year = year(time))      %>% 
                group_by(case,desc,year,
                         pft,dbh)              %>% 
                select(-time)                  %>% 
                summarize_all(mean,na.rm=TRUE) %>% 
                ungroup()                      %>% 
                mutate(fates_ddbh = fates_ddbh/fates_nplant)

ctrl_ddbh_mod = ddbh_szpf_mod                  %>% 
                filter(case %in% c(1,5,9) &
                       !dbh %in% c(1:3) &
                         pft!=4)               %>% 
                select(case,desc,pft,
                       dbh,fates_ddbh)         %>% 
                group_by(case,desc,pft,dbh)    %>% 
                mutate(fates_ddbh = mean(fates_ddbh,
                                         na.rm=TRUE),
                       sample_n = sum(!is.na(fates_ddbh))) %>% 
                ungroup() %>% distinct()
ctrl_ddbh_sd_mod = ddbh_szpf_mod                  %>% 
                   filter(case %in% c(1,5,9) &
                       !dbh %in% c(1:3)&
                         pft!=4)                  %>% 
                   select(case,desc,pft,
                          dbh,fates_ddbh)         %>% 
                   group_by(case,desc,pft,dbh)    %>% 
                   mutate(fates_ddbh = sd(fates_ddbh,
                                          na.rm=TRUE)) %>% 
                   ungroup() %>% distinct()      %>% 
                   rename(ddbh_sd = fates_ddbh)

ctrl_ddbh_mod = ctrl_ddbh_mod %>% left_join(ctrl_ddbh_sd_mod,by=c("case","desc","pft","dbh"))

ctrl_ddbh_mod$margin_error = unlist(mapply(n=ctrl_ddbh_mod$sample_n,
                                        mean = ctrl_ddbh_mod$fates_ddbh,
                                        sd = ctrl_ddbh_mod$ddbh_sd,CI95_error))
ctrl_ddbh_mod  = ctrl_ddbh_mod                   %>% 
                 mutate(lwr_ddbh = fates_ddbh - margin_error,
                        upr_ddbh = fates_ddbh + margin_error)
ctrl_ddbh_mod  = ctrl_ddbh_mod                        %>% 
                 mutate(site=site_grab(desc))         %>%    
                 select(site,pft,dbh,
                        fates_ddbh,lwr_ddbh,upr_ddbh) %>% 
                 mutate(type="Model") 

ctrl_ddbh_obs = fread(file.path(obs_path,"ctrl-ddbh-obs.csv"))

ctrl_ddbh_obs  = ctrl_ddbh_obs                     %>% 
                 rename(
                     pft = PFT,
                     dbh = DBH,
                fates_ddbh = Mean_cm,
                lwr_ddbh   = low95CI,
                upr_ddbh   = high95CI) %>% 
              filter(
                       !pft %in% c("white_pine") &
                        dbh != 120) %>% 
              mutate(type="Observation",
                     pft = case_when(pft=="yellow_pine" ~ 1,
                                     pft=="cedar" ~ 2,
                                     pft=="fir" ~ 3),
                     dbh = case_when(dbh<=15 ~ 5,
                                     dbh<=30 ~ 6,
                                     dbh<=45 ~ 8,
                                     dbh<=60 ~ 9,
                                     dbh<=75 ~ 11,
                                     dbh<=90 ~ 12,
                                     dbh>100 ~ 13))
ctrl_ddbh_mod = rbind(ctrl_ddbh_mod,ctrl_ddbh_obs)
plot_df = ctrl_ddbh_mod

plot_df$dbh = factor(plot_df$dbh,levels=unique(plot_df$dbh))
plot_df$pft = factor(plot_df$pft,levels=unique(plot_df$pft))
pft_keys = pftinfo$short[1:3]
names(pft_keys) = c(1:3)

gg_now = ggplot(plot_df,aes(x=dbh,y=fates_ddbh,fill=type)) 
gg_now = gg_now + facet_wrap(site~pft, labeller=labeller(pft=pft_keys), ncol=3)
gg_now = gg_now + geom_bar(position=position_dodge(),stat="identity",width=0.6) 
gg_now = gg_now + geom_errorbar(aes(ymin=fates_ddbh-lwr_ddbh,
                         ymax=fates_ddbh+upr_ddbh),
                     width=0.2,
                     position=position_dodge(0.6))
  
gg_now = gg_now + scale_fill_manual(values=c("grey","grey50"))
gg_now = gg_now + scale_x_discrete(labels=dbh_labs[4:13])
gg_now = gg_now + ylab(expression("Growth rate"~"("~cm~plant^-1~yr^-1~")"))
gg_now = gg_now + xlab("Size class (cm)") 
gg_now = gg_now + theme_grey( base_size = gg_ptsz, base_family = "Helvetica",
                                base_line_size = 0.5,base_rect_size =0.5) 
gg_now = gg_now + theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm")
                                              , angle = 90
                                              , hjust = 1)#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

for (d in sequence(ndevice)){
    f_output = paste0("ddbh_ctrl_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = gg_now
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.8
                    , height   = gg_height*0.8
                    , units    = gg_units
                    , dpi      = gg_depth
    )
    }



## benchmark relative change in groth rate for treatments

ddbh_pft = data.table::fread(file.path(main_path,model_file_name[3]))
ddbh_pft = ddbh_pft                                                   %>% 
           dplyr::select(case,desc,pft,time,fates_ddbh,fates_nplant)
ddbh_pft = ddbh_pft                            %>% 
           mutate(fates_ddbh = ifelse(fates_nplant==0,NA,fates_ddbh*ha_2_m2),
                  year = year(time))
ddbh_pft = ddbh_pft                       %>% 
           group_by(case,desc,pft,year)   %>% 
           select(-time)                  %>%
           summarize_all(mean,na.rm=TRUE) %>% 
           ungroup()

ddbh_df = ddbh_pft

ddbh_vars = names(ddbh_df)[grepl("ddbh",names(ddbh_df))]
n_ddbh = length(ddbh_vars)
for(v in sequence(n_ddbh)){
  var_now = ddbh_vars[v]
  ddbh_df[[var_now]] = ddbh_scale_fun(ddbh_df,var_now)
}

ctrl_ddbh = ddbh_df                     %>% 
            filter(case %in% c(1,5,9))  %>% 
            group_by(case,desc)         %>% 
            slice(rep(seq_len(n()),times = nsites)) %>% ungroup()

ddbh_pft_vars = c("fates_ddbh")
ddbh_pft_desc = c("growth rate")

n_delta = length(ddbh_pft_vars)


ctrl_ddbh =  ctrl_ddbh                       %>% 
              dplyr::select(all_of(ddbh_pft_vars)) %>% 
              rename_at(vars(fates_ddbh),rename_fun)

treat_ddbh = ddbh_df                                   %>% 
              filter(!case%in% c(1,5,9))             

treat_ddbh = treat_ddbh %>% dplyr::select(all_of(c("case",
                                              "year",
                                              "pft",
                                              "desc",
                                              ddbh_pft_vars)))
    

delta_ddbh_pft = cbind(treat_ddbh,ctrl_ddbh)
delta_ddbh_pft = delta_ddbh_pft                    %>% 
              mutate(site=site_grab(desc))
delta_ddbh_pft$treatment = unlist(lapply(delta_ddbh_pft$desc,treatment_grab))

delta_ddbh_pft = delta_ddbh_pft                             %>% 
                 mutate(fates_ddbh = fates_ddbh/ctrl_ddbh)  %>% 
                 select(-ctrl_ddbh)

treated_case = unique(delta_ddbh_pft$case)

ddbhbypft_mean = NULL
ddbhbypft_sd   = NULL


for(n in treated_case){
  delta_now = delta_ddbh_pft %>% filter(case==n)
 
  
    mean_pft  = delta_now                                                %>% 
               dplyr::select(-c(year,case,desc))                         %>% 
               group_by(site,treatment,pft)                              %>% 
               mutate(fates_ddbh = mean(fates_ddbh,na.rm=TRUE),
                         sample_n = sum(!is.na(fates_ddbh)))             %>%  
               ungroup() %>% distinct()
    
    ddbhbypft_mean = rbind(ddbhbypft_mean,mean_pft)
    
    sd_pft  = delta_now                                                 %>% 
               dplyr::select(-c(year,case,desc))                        %>% 
               group_by(site,treatment,pft)                              %>% 
               summarize_all(sd,na.rm=TRUE) %>% ungroup()
    
    ddbhbypft_sd = rbind(ddbhbypft_sd,sd_pft)
    
     
}


model_ddbh = ddbhbypft_mean
model_ddbh_sd = ddbhbypft_sd %>% rename(sd_ddbh = fates_ddbh)
model_ddbh = model_ddbh %>% left_join(model_ddbh_sd, by=c("site","treatment","pft"))


model_ddbh$margin_error = unlist(mapply(n=model_ddbh$sample_n,
                                        mean = model_ddbh$fates_ddbh,
                                        sd = model_ddbh$sd_ddbh,CI95_error))
model_ddbh  = model_ddbh                   %>% 
              mutate(lwr_ddbh = fates_ddbh - margin_error,
                     upr_ddbh = fates_ddbh + margin_error)
model_ddbh  = model_ddbh                                                          %>% 
              select(site,treatment,pft,fates_ddbh,lwr_ddbh,upr_ddbh)             %>% 
              mutate(type = case_when(treatment=="Burn-Cool" ~ "Model-BurnCool",
                                      treatment=="Burn-Hot" ~ "Model-BurnHot",
                                      treatment=="Thin" ~ "Model-Thin"),
                         treatment = ifelse(treatment=="Thin", treatment, "Burn")) %>% 
              filter(pft!=4)

obs_ddbh = fread(file.path(obs_path,"ddbh-obs.csv"))
obs_ddbh = obs_ddbh                     %>% 
                 rename(
                   treatment = Treatment, 
                   pft = PFT,
                   fates_ddbh = Multiplier_mean,
                   lwr_ddbh   = Multiplier_low95CI,
                   upr_ddbh   = Multiplier_high95CI) %>% 
              filter(pft !="white_pine" &
                     treatment !="Burn+Thin") %>% 
              mutate(type="Observation",
                     pft = case_when(pft=="yellow_pine" ~ 1,
                                     pft=="cedar" ~ 2,
                                     pft=="fir" ~ 3))  

model_ddbh = rbind(model_ddbh,obs_ddbh)
plot_df = model_ddbh
plot_df$pft = factor(plot_df$pft,levels=unique(plot_df$pft))
pft_labs = pftinfo$short
names(pft_labs)=c(1:4)



ddbh_pft_plot  = ggplot(plot_df,aes(x=pft,y=fates_ddbh,
                   fill=type)) +
       facet_wrap(treatment~site) +              
       geom_bar(position=position_dodge(),stat="identity",width=0.6) +
       geom_errorbar(aes(ymin=lwr_ddbh,
                         ymax=upr_ddbh),
                     width=0.2,
                     position=position_dodge(0.6))+
       scale_x_discrete(labels=pft_labs)+
       scale_fill_manual(values=c("Model-BurnCool" = "#836B43",
                                  "Model-BurnHot" = "#D68D18",
                                  "Model-Thin" = "#A0AE6A",
                                 "Observation" = "#437683"))+
       ylab("Treated to control growth rate ratio") +
       xlab("") +
       theme_grey( base_size = gg_ptsz, base_family = "Helvetica",base_line_size = 0.5,base_rect_size =0.5) +
       theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

 for (d in sequence(ndevice)){
    f_output = paste0("ddbh_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = ddbh_pft_plot
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.6
                    , height   = gg_height*0.8
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
   }




```




```{r MortalityByPFTBenchmark}

mod_mortpft = bypft                          %>% 
              select(case,desc,year,pft,
                     fates_mortality)        %>% 
              group_by(case,desc,year,pft)   %>% 
              summarize_all(mean,na.rm=TRUE) %>% 
              ungroup()

mod_mortpft = mod_mortpft                   %>% 
              mutate(site=site_grab(desc))

bldgt = mod_mortpft                        %>% 
        filter(site=="Blodgett")           %>% 
        mutate(yr_group = cut(year,breaks=c(-Inf,2003,2009,2016,Inf),
                              labels=c("2001-2003","2004-2009",
                                       "2010-2016","2017-2020")))
bldgt_sum_pft = bldgt                      %>% 
        group_by(desc,site,pft,yr_group)   %>% 
        select(-c(case,year))              %>% 
        summarize_all(sum,na.rm=TRUE)      %>% 
        ungroup()
bldgt_sum = bldgt                      %>% 
        group_by(desc,site,yr_group)   %>% 
        select(-c(case,year,pft))      %>% 
        summarize_all(sum,na.rm=TRUE)  %>% 
        ungroup()


stef = mod_mortpft                         %>% 
       filter(site=="STEF")                %>% 
       mutate(yr_group = cut(year,breaks=c(-Inf, 2014, 2016, 2018,Inf),
                             labels=c("2011-2014","2015-2016",
                                      "2017-2018","2018-2020")))


stef_sum_pft = stef                        %>% 
       group_by(desc,site,pft,yr_group)    %>% 
       select(-c(case,year))               %>% 
       summarize_all(sum,na.rm=TRUE)       %>% 
       ungroup()                           %>% 
       filter(yr_group!="2018-2020")
stef_sum = stef                        %>% 
       group_by(desc,site,yr_group)    %>% 
       select(-c(case,year,pft))       %>% 
       summarize_all(sum,na.rm=TRUE)   %>% 
       ungroup()                       %>% 
       filter(yr_group!="2018-2020")

tea = mod_mortpft                          %>% 
       filter(site=="Teakettle")           %>% 
       mutate(yr_group = cut(year,breaks=c(-Inf, 2003, 2011, 2018,2019,Inf),
                             labels=c("2001-2003","2004-2011",
                                      "2012-2018","2018-2019","2019-2020")))
tea_sum_pft = tea                          %>% 
          group_by(desc,site,pft,yr_group) %>% 
          select(-c(case,year))            %>% 
          summarize_all(sum,na.rm=TRUE)    %>% 
          ungroup()                        %>% 
          filter(yr_group!="2019-2020")
tea_sum = tea                              %>% 
          group_by(desc,site,yr_group)     %>% 
          select(-c(case,year,pft))        %>% 
          summarize_all(sum,na.rm=TRUE)    %>% 
          ungroup()                        %>% 
          filter(yr_group!="2019-2020")   


mod_mortpft_yr = rbind(bldgt_sum_pft,stef_sum_pft,tea_sum_pft)
mod_mortpft_yr$treatment = unlist(lapply(mod_mortpft_yr$desc,treatment_grab))
mod_mortpft_yr = mod_mortpft_yr %>% select(-desc)
mod_mortpft_sum = mod_mortpft_yr           %>% 
          select(-yr_group)                %>% 
          group_by(site,treatment,pft)     %>% 
          summarize_all(sum,na.rm=TRUE)    %>% 
          ungroup()


mod_mortpft_yr$se_mortality = 0

mod_mortpft_yr = mod_mortpft_yr            %>% 
                 mutate(type = case_when(treatment=="Burn-Cool" ~ "Model-BurnCool",
                                      treatment=="Burn-Hot" ~ "Model-BurnHot",
                                      treatment=="Thin" ~ "Model-Thin",
                                      treatment=="None" ~ "Model-Control"),
                        treatment = ifelse(treatment %in% c("Thin","None"), treatment, "Burn"))
mod_mortpft_sum = mod_mortpft_sum         %>% 
                  mutate(type = case_when(treatment=="Burn-Cool" ~ "Model-BurnCool",
                                      treatment=="Burn-Hot" ~ "Model-BurnHot",
                                      treatment=="Thin" ~ "Model-Thin",
                                      treatment=="None" ~ "Model-Control"),
                        treatment = ifelse(treatment %in% c("Thin","None"), treatment, "Burn"))
                 
mod_mortpft_sum$se_mortality = NA

     

obs_mort = fread(file.path(obs_path,"mort-obs.csv"))

obs_mort    = obs_mort                            %>% 
              select(site,Treatment,Category,
                     start_yr,end_yr,prob,SE,
                     Category,IncludesPreTreat,
                     Timeframe)                   %>% 
              rename(treatment = Treatment,
                     fates_mortality = prob,
                     se_mortality = SE)           %>% 
              filter(treatment!="Burn+Thin")      %>% 
              mutate(yr_group = paste(start_yr,end_yr,
                                      sep="-"))   

obs_mort = obs_mort                         %>% 
           mutate(yr_group=case_when(yr_group=="2001-2003" ~ "2001-2003",
                                     yr_group=="2003-2009" ~ "2004-2009",
                                     yr_group=="2009-2016" ~ "2010-2016",
                                     yr_group=="2016-2020" ~ "2017-2020",
                                     yr_group=="2012-2014" ~ "2011-2014",
                                     yr_group=="2014-2016" ~ "2015-2016",
                                     yr_group=="2016-2018" ~ "2017-2018",
                                     yr_group=="2000.26579301075-2003.73420698925" ~ "2001-2003",
                                     yr_group=="2003.71395705521-2011" ~ "2004-2011",
                                     yr_group=="2011-2018.31741409435" ~ "2012-2018"),
                     fates_mortality = fates_mortality*100,
                     se_mortality    = se_mortality*100)  %>% 
                     filter(!is.na(yr_group))
                     
obs_mortpft_sum = obs_mort                         %>% 
                  filter(Category %in% c("pine",
                                         "cedar",
                                         "fir",
                                         "oak"))   %>% 
              rename(pft = Category)               %>% 
              mutate(pft=case_when(pft=="pine" ~ 1,
                                   pft=="cedar" ~ 2,
                                   pft=="fir" ~ 3,
                                   pft=="oak" ~ 4)) %>% 
              select(-c(yr_group,Timeframe,
                        IncludesPreTreat,
                        start_yr,end_yr))          %>% 
              group_by(site,treatment,pft)         %>% 
              summarize_all(sum,na.rm=TRUE)        %>% 
              ungroup()                            %>% 
              mutate(type="Observation")

obs_mortpft_yr = obs_mort                         %>% 
                  filter(Category %in% c("pine",
                                         "cedar",
                                         "fir",
                                         "oak"))   %>% 
              rename(pft = Category)               %>% 
              mutate(pft=case_when(pft=="pine" ~ 1,
                                   pft=="cedar" ~ 2,
                                   pft=="fir" ~ 3,
                                   pft=="oak" ~ 4)) %>% 
              select(-c(Timeframe,
                        IncludesPreTreat,
                        start_yr,end_yr))          %>% 
              group_by(site,treatment,pft,yr_group)%>% 
              summarize_all(sum,na.rm=TRUE)        %>% 
              ungroup()                            %>% 
              mutate(type = "Observation")

    
mod_mortpft_yr = rbind(mod_mortpft_yr,obs_mortpft_yr)
mod_mortpft_sum = rbind(mod_mortpft_sum,obs_mortpft_sum)

mod_mortpft_yr = mod_mortpft_yr                   %>% 
              mutate(treatment=if_else(treatment=="None", "Control", treatment))

mod_mortpft_sum = mod_mortpft_sum                  %>% 
              mutate(treatment=if_else(treatment=="None", "Control", treatment))
plot_df = mod_mortpft_yr
plot_df$pft = factor(plot_df$pft,levels=unique(plot_df$pft))
pft_labs = pftinfo$short
names(pft_labs)=c("1","2","3","4")
pft_colour = pftinfo$colour

n_plot = length(unique(plot_df$site))

for(n in sequence(n_plot)){
  site_now = unique(plot_df$site)[n]
  df_now = plot_df %>% filter(site==site_now)
  mortpft_plot  = ggplot(df_now,aes(x=yr_group,y=fates_mortality,
                   fill=type)) +
       facet_wrap(pft~treatment, ncol= 3, labeller = labeller(pft=pft_labs)) +              
       geom_bar(position=position_dodge(),stat="identity",width=1) +
       scale_fill_manual(values=c("Model-BurnCool" = "#836B43",
                                  "Model-BurnHot" = "#D68D18",
                                  "Model-Thin" = "#A0AE6A",
                                  "Model-Control" = "#18B0D6",
                                  "Observation" = "#437683"))+
       ylab("Summed mortality rate") +
       xlab("") +
       #labs(title = site_now)+
       theme_grey( base_size = gg_ptsz, base_family = "Helvetica",base_line_size = 0.5,base_rect_size =0.5) +
       theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm")
                                              , angle = 90
                                              , hjust = 1)#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

 for (d in sequence(ndevice)){
    f_output = paste0(site_now,"mortpftyr_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = mortpft_plot
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.8
                    , height   = gg_height*1.1
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
   }



}

plot_df = mod_mortpft_sum
plot_df$pft = factor(plot_df$pft,levels=unique(plot_df$pft))
plot_df$treatment = factor(plot_df$treatment,levels=c("Control","Burn","Thin"))

  mortsum_plot  = ggplot(plot_df,aes(x=pft,y=fates_mortality,
                   fill=type)) +
       facet_wrap(site~treatment,ncol=3) +
       geom_bar(position=position_dodge(),stat="identity",width=0.6) +
       #geom_errorbar(aes(ymin=fates_mortality-sd_mortality,
      #                   ymax=fates_mortality+sd_mortality),
       #              width=0.2,
      #               position=position_dodge(0.6))+
       scale_x_discrete(labels=pft_labs)+
       scale_fill_manual(values=c("Model-BurnCool" = "#836B43",
                                  "Model-BurnHot" = "#D68D18",
                                  "Model-Thin" = "#A0AE6A",
                                  "Model-Control" = "#18B0D6",
                                  "Observation" = "#437683"))+
       ylab("Summed mortality rate") +
       xlab("") +
       theme_grey( base_size = gg_ptsz, base_family = "Helvetica",base_line_size = 0.5,base_rect_size =0.5) +
       theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

 for (d in sequence(ndevice)){
    f_output = paste0("mortsum_pftbenchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = mortsum_plot
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.7
                    , height   = gg_height*0.8
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
   }


 

 

```







```{r MortalityBySizeBenchmark}

mod_mort_dbh  = bydbh_na                          %>% 
                select(all_of(c("case","desc",
                                "year","dbh",
                              mortout_dbh[1:8]))) %>% 
                filter(dbh %in% c(4:13))          %>% 
                mutate(dbh_grp = cut(dbh,breaks=c(-Inf,8,Inf),
                                 labels=c("DBH <= 60cm","DBH > 60cm")),
                       site = site_grab(desc))
mod_mort_dbh$fates_mortality = mod_mort_dbh %>% dplyr::select(starts_with("fates_mortality")) %>% rowSums()

bldgt = mod_mort_dbh                       %>% 
        filter(site=="Blodgett")           %>% 
        mutate(yr_group = cut(year,breaks=c(-Inf,2003,2009,2016,Inf),
                              labels=c("2001-2003","2004-2009",
                                       "2010-2016","2017-2020"))) %>% 
        select(case,desc,site,yr_group,dbh_grp,fates_mortality)        %>% 
        group_by(case,desc,site,yr_group,dbh_grp) %>% 
        summarize_all(sum,na.rm=TRUE)        %>% 
        ungroup()

stef = mod_mort_dbh                         %>% 
       filter(site=="STEF")                %>% 
       mutate(yr_group = cut(year,breaks=c(-Inf, 2014, 2016, 2018,Inf),
                             labels=c("2011-2014","2015-2016",
                                      "2017-2018","2018-2020")))  %>%
       select(case,desc,site,yr_group,dbh_grp,fates_mortality)        %>% 
       group_by(case,desc,site,yr_group,dbh_grp) %>% 
       summarize_all(sum,na.rm=TRUE)        %>% 
       ungroup()                            %>% 
       filter(yr_group != "2018-2020")

tea = mod_mort_dbh                          %>% 
       filter(site=="Teakettle")            %>% 
       mutate(yr_group = cut(year,breaks=c(-Inf, 2003, 2011, 2018,2019,Inf),
                             labels=c("2001-2003","2004-2011",
                                      "2012-2018","2018-2019","2019-2020"))) %>% 
       select(case,desc,site,yr_group,dbh_grp,fates_mortality)        %>% 
       group_by(case,desc,site,yr_group,dbh_grp) %>% 
       summarize_all(sum,na.rm=TRUE)        %>% 
       ungroup()                            %>% 
       filter(!yr_group %in% c("2018-2019",
                              "2019-2020"))

mod_mortdbh_yr = rbind(bldgt,stef,tea)
mod_mortdbh_yr$treatment = unlist(lapply(mod_mortdbh_yr$desc,treatment_grab))
mod_mortdbh_yr  =  mod_mortdbh_yr                     %>% 
                   mutate(type = case_when(treatment=="Burn-Cool" ~ "Model-BurnCool",
                                      treatment=="Burn-Hot" ~ "Model-BurnHot",
                                      treatment=="Thin" ~ "Model-Thin",
                                      treatment=="None" ~ "Model-Control"),
                        treatment = ifelse(treatment %in% c("Thin","None"), treatment, "Burn"))
mod_mortdbh_yr$se_mortality = NA
mod_mortdbh_yr = mod_mortdbh_yr %>% select(-c(case,desc))


obs_mort_dbh = obs_mort                                 %>% 
               filter(Category %in% c("<60cm",">60cm")) %>% 
               select(site,treatment,yr_group,Category,
                      fates_mortality,se_mortality)     %>% 
               rename(dbh_grp = Category)               %>% 
               mutate(dbh_grp = case_when(dbh_grp == "<60cm" ~ "DBH <= 60cm",
                                          dbh_grp == ">60cm" ~ "DBH > 60cm"),
                      type = "Observation")

mod_mortdbh_yr = rbind(mod_mortdbh_yr,obs_mort_dbh)
mod_mortdbh_yr = mod_mortdbh_yr %>% mutate(treatment=ifelse(
  treatment=="None", "Control", treatment))

plot_df = mod_mortdbh_yr
plot_df$treatment = factor(plot_df$treatment,levels=c("Control","Burn","Thin"))
sites = unique(plot_df$site)
gg_list = list()
for(n in sequence(nsites)){
  site_now = sites[n]
  df_now = plot_df %>% filter(site == site_now)
  mortdbh_plot  = ggplot(df_now,aes(x=yr_group,y=fates_mortality,
                   fill=type)) +
       facet_wrap(dbh_grp~treatment,ncol=3) +
       geom_bar(position=position_dodge(),stat="identity",width=0.6) +
       geom_errorbar(aes(ymin=fates_mortality-se_mortality,
                         ymax=fates_mortality+se_mortality),
                    width=0.2,
                    position=position_dodge(0.6))+
       scale_fill_manual(values=c("Model-BurnCool" = "#836B43",
                                  "Model-BurnHot" = "#D68D18",
                                  "Model-Thin" = "#A0AE6A",
                                  "Model-Control" = "#18B0D6",
                                  "Observation" = "#437683"))+
       ylab(paste(site_now,"summed mortality rate (%)",sep=" ")) +
       xlab("") +
       theme_grey( base_size = gg_ptsz, base_family = "Helvetica",base_line_size = 0.5,base_rect_size =0.5) +
       theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm")
                                              , angle = 90
                                              , hjust = 1)#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

 for (d in sequence(ndevice)){
    f_output = paste0(site_now,"_mortdbh_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = mortdbh_plot
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.8
                    , height   = gg_height
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
 }

  gg_list[[n]] = mortdbh_plot
  
}

gg_patch = wrap_plots(gg_list[[1]], gg_list[[2]], gg_list[[3]]) +
  plot_layout(guides="collect",ncol=3) & theme(legend.position="bottom")

for (d in sequence(ndevice)){
    f_output = paste0("mortdbhyear_sites_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = gg_patch
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*1.1
                    , height   = gg_height
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
 }








```






```{r CumulativeMortalityBenchmark}

mod_mortsum = data.table::fread(file.path(main_path,model_file_name[4]))
obs_mortsum = fread(file.path(obs_path,"mort-obs.csv"))
obs_mortsum = obs_mortsum %>% filter(Timeframe == "Study mortality" &
                                     Category %in% c("<60cm",">60cm") &
                                     Treatment != "Burn+Thin")

mod_mortsum = mod_mortsum                            %>% 
              select(-c(fates_mortality_rxcambial,
                        fates_mortality_rxcrown))    %>% 
              mutate(site = site_grab(desc))

mod_mortsum$fates_mortality = mod_mortsum %>% dplyr::select(starts_with("fates_mortality")) %>% rowSums()


bldgt = mod_mort_dbh                       %>% 
        filter(site=="Blodgett")           %>% 
        select(case,desc,site,dbh_grp,
               fates_mortality)            %>% 
        group_by(case,desc,site,dbh_grp)   %>% 
        summarize_all(sum,na.rm=TRUE)      %>% 
        ungroup()

stef = mod_mort_dbh                         %>% 
       filter(site=="STEF" &
              year %in% c(2012:2018))       %>% 
       select(case,desc,site,dbh_grp,
              fates_mortality)              %>% 
       group_by(case,desc,site,dbh_grp)     %>% 
       summarize_all(sum,na.rm=TRUE)        %>% 
       ungroup()                           

tea = mod_mort_dbh                          %>% 
       filter(site=="Teakettle" &
              year %in% c(2000:2018))       %>%
       select(case,desc,site,dbh_grp,
              fates_mortality)              %>% 
       group_by(case,desc,site,dbh_grp)     %>% 
       summarize_all(sum,na.rm=TRUE)        %>% 
       ungroup()                           

mod_mortsum = rbind(bldgt,stef,tea)
mod_mortsum$treatment = unlist(lapply(mod_mortsum$desc,treatment_grab))
mod_mortsum  =  mod_mortsum                     %>% 
                mutate(type = case_when(treatment=="Burn-Cool" ~ "Model-BurnCool",
                                      treatment=="Burn-Hot" ~ "Model-BurnHot",
                                      treatment=="Thin" ~ "Model-Thin",
                                      treatment=="None" ~ "Model-Control"),
                        treatment = ifelse(treatment %in% c("Thin","None"), treatment, "Burn"))
mod_mortsum$se_mortality = NA
mod_mortsum = mod_mortsum %>% select(-c(case,desc))

obs_mortsum = obs_mortsum                               %>% 
               select(site,Treatment,Category,
                      prob,SE)                          %>% 
               rename(dbh_grp = Category,
                      treatment = Treatment,
                      fates_mortality = prob,
                      se_mortality = SE)               %>% 
               mutate(dbh_grp = case_when(dbh_grp == "<60cm" ~ "DBH <= 60cm",
                                          dbh_grp == ">60cm" ~ "DBH > 60cm"),
                      type = "Observation",
                      fates_mortality = fates_mortality*100,
                      se_mortality = se_mortality*100)


mod_mortsum = rbind(mod_mortsum,obs_mortsum)

mod_mortsum = mod_mortsum %>% mutate(treatment = ifelse(treatment=="None","Control",treatment))


plot_df = mod_mortsum
plot_df$treatment = factor(plot_df$treatment,levels=c("Control","Burn","Thin"))

mortsum_plot  = ggplot(plot_df,aes(x=dbh_grp,y=fates_mortality,
                   fill=type)) +
       facet_wrap(site~treatment,ncol=3) +
       geom_bar(position=position_dodge(),stat="identity",width=0.6) +
       geom_errorbar(aes(ymin=fates_mortality-se_mortality,
                         ymax=fates_mortality+se_mortality),
                    width=0.2,
                    position=position_dodge(0.6))+
       scale_fill_manual(values=c("Model-BurnCool" = "#836B43",
                                  "Model-BurnHot" = "#D68D18",
                                  "Model-Thin" = "#A0AE6A",
                                  "Model-Control" = "#18B0D6",
                                  "Observation" = "#437683"))+
       ylab(paste(site_now,"summed mortality rate (%)",sep=" ")) +
       xlab("") +
       theme_grey( base_size = gg_ptsz, base_family = "Helvetica",base_line_size = 0.5,base_rect_size =0.5) +
       theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm")
                                              , angle = 90
                                              , hjust = 1)#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

 for (d in sequence(ndevice)){
    f_output = paste0("mortsum_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = mortsum_plot
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.8
                    , height   = gg_height
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
 }
                


```



```{r FuelBenchmark}

## Benchmark fuel load for control case
mod_fuel_df =   fuel                         %>% 
                mutate(year=year(time))      %>% 
                select(case,desc,year,fuel,
                       fates_fuel_amount)    

mod_fuel_bldgt = mod_fuel_df                    %>% 
                 filter(year %in% c(2001,2003) &
                        case %in% c(1:4))       %>% 
                 select(-year)

bldgt_fuel_ctrl = mod_fuel_bldgt               %>% 
                filter(case==1)                %>% 
                group_by(case,desc,fuel)       %>% 
                summarize_all(mean,na.rm=TRUE) %>% 
                ungroup() 

bldgt_fuel_se = mod_fuel_bldgt                 %>% 
                filter(case==1)                %>% 
                group_by(case,desc,fuel)       %>%
                summarize_each(funs(se=sd(.)/sqrt(n()))) %>% 
                ungroup() 
bldgt_fuel_ctrl = bldgt_fuel_ctrl %>% left_join(bldgt_fuel_se,
                                                by=c("case","desc","fuel"))
bldgt_fuel_ctrl = bldgt_fuel_ctrl %>% filter(fuel %in% c(1:3))

mod_fuel_stef  = mod_fuel_df                 %>% 
                 filter(year == 2014 &
                        case %in% c(5:8))    %>% 
                 select(-year)
stef_fuel_ctrl = mod_fuel_stef                  %>% 
                 filter(case==5)                %>% 
                 group_by(case,desc,fuel)       %>% 
                 summarize_all(mean,na.rm=TRUE) %>% 
                 ungroup()
stef_fuel_se = mod_fuel_stef                    %>% 
               filter(case==5)                  %>% 
               group_by(case,desc,fuel)         %>%
               summarize_each(funs(se=sd(.)/sqrt(n()))) %>% 
               ungroup() 
stef_fuel_ctrl = stef_fuel_ctrl %>% left_join(stef_fuel_se,
                                              by=c("case","desc","fuel"))
stef_fuel_ctrl = stef_fuel_ctrl %>% filter(fuel %in% c(1:3,5))

mod_fuel_tea = mod_fuel_df                    %>% 
              filter(year %in% c(2003) &
                        case %in% c(9:12))       %>% 
                select(-year)

tea_fuel_ctrl = mod_fuel_tea                   %>% 
                filter(case==9)                %>% 
                group_by(case,desc,fuel)       %>% 
                summarize_all(mean,na.rm=TRUE) %>% 
                ungroup() 

tea_fuel_se =   mod_fuel_tea                   %>% 
                filter(case==1)                %>% 
                group_by(case,desc,fuel)       %>%
                summarize_each(funs(se=sd(.)/sqrt(n()))) %>% 
                ungroup() 
tea_fuel_ctrl = tea_fuel_ctrl %>% left_join(tea_fuel_se,
                                                by=c("case","desc","fuel"))
tea_fuel_ctrl = tea_fuel_ctrl %>% filter(fuel %in% c(1:3))

mod_fuel_ctrl  = rbind(bldgt_fuel_ctrl,stef_fuel_ctrl,tea_fuel_ctrl)
  
mod_fuel_ctrl$treatment = unlist(lapply(mod_fuel_ctrl$desc,treatment_grab)) 
mod_fuel_ctrl = mod_fuel_ctrl %>% mutate(site=site_grab(desc),
                                         type = case_when(treatment=="Burn-Cool" ~ "Model-BurnCool",
                                                          treatment=="Burn-Hot" ~ "Model-BurnHot",
                                                          treatment=="Thin" ~ "Model-Thin",
                                                          treatment=="None" ~ "Model"),
                                         treatment = ifelse(treatment %in% c("Thin","None"), treatment, "Burn"))
mod_fuel_ctrl = mod_fuel_ctrl %>% select(-c(case,desc))

obs_fuel   = fread(file.path(obs_path,"fuel-obs.csv"))
obs_fuel_ctrl = obs_fuel                           %>% 
                select(site,Treatment,Fuel_class,
                        Fuel_load,SE,
                        Fuel_biomass)              %>% 
                mutate_at(vars(Fuel_load,Fuel_biomass),
                          na_to_zero)              %>% 
                mutate(Fuel_load = Fuel_load + Fuel_biomass) %>% 
                mutate_at(vars(Fuel_load,Fuel_biomass),
                          zero_to_na)
                
 obs_fuel_ctrl = obs_fuel_ctrl                             %>% 
                 filter(Fuel_class%in%c("ONE_HOUR_FUELS",
                                        "TEN_HOUR_FUELS",
                                        "HUNDRED_HOUR_FUELS",
                                        "Litter",
                                        "1-hr",
                                        "10-hr",
                                        "100-hr") &
                        Treatment=="None")        %>% 
                 select(-Fuel_biomass)            %>% 
                 rename(treatment = Treatment,
                        fuel = Fuel_class,
                        fates_fuel_amount = Fuel_load,
                        se = SE)    %>% 
                 mutate(fuel = case_when(fuel %in% c("ONE_HOUR_FUELS","1-hr") ~ "1",
                                         fuel %in% c("TEN_HOUR_FUELS","10-hr") ~ "2",
                                         fuel %in% c("HUNDRED_HOUR_FUELS","100-hr") ~ "3",
                                         fuel=="Litter" ~ "5")) %>% 
                group_by(site,treatment,fuel)                   %>% 
                summarize_all(mean,na.rm=TRUE)                  %>% 
                ungroup()

                
obs_fuel_ctrl = obs_fuel_ctrl %>% mutate(type="Observation")
obs_fuel_ctrl = obs_fuel_ctrl %>% 
                mutate_at(vars(fates_fuel_amount:se),
                                            ~.x*mass_2_carbon*mgha_2_kgm2) #convert to kg/m2 and to carbon .

mod_fuel_ctrl = rbind(mod_fuel_ctrl,obs_fuel_ctrl)
plot_df = mod_fuel_ctrl 
plot_df$fuel   = factor(plot_df$fuel,levels=unique(plot_df$fuel))
f_colfuels   = fuelinfo$colour[c(1:3,5)]
f_fuellabs   = fuelinfo$short[c(1:3,5)]
names(f_fuellabs) = c(1,2,3,5)

plot_vars = c("fates_fuel_amount")
plot_desc = c("Fuel load by fuel class")
unit = quote(kgC~m^-2)
n_plot = length(plot_vars)
for(n in sequence(n_plot)){
  var_now = plot_vars[n]
  desc_now = plot_desc[n]
  gg_now = ggplot(plot_df,aes_string(x="type",y=var_now,fill="fuel")) 
  gg_now = gg_now + geom_bar(stat="identity",width=0.6) 
  gg_now = gg_now + facet_wrap(.~site)
  gg_now = gg_now + scale_fill_manual(name=element_blank(),labels=f_fuellabs,values=f_colfuels)
  gg_now = gg_now + ylab(bquote(.(desc_now)~"("~.(unit)~")"))
  gg_now = gg_now + xlab(" ") 
  gg_now = gg_now + theme_grey( base_size = gg_ptsz, base_family = "Helvetica",
                                base_line_size = 0.5,base_rect_size =0.5) 
  gg_now = gg_now + theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

 for (d in sequence(ndevice)){
    f_output = paste0(var_now,"_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = gg_now
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.6
                    , height   = gg_height*0.6
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
   }

    
  
  
}


## benchmark relative change in treated units compared to control

ctrl_fuel = fuel_df %>% filter(case %in% c(1,5,9))
ctrl_fuel = ctrl_fuel                      %>% 
            group_by(case,desc)            %>% 
            slice(rep(seq_len(n()),times = 3)) %>% ungroup()


fuel_vars = c("fates_fuel_notrunk",
              "fates_fuel_litter",
              "fates_fuel_cwd")
fuel_desc = c("total fuel load",
              "total dead fine fuels",
              "coarse woody debris")

n_fuel = length(fuel_vars)


ctrl_fuel =  ctrl_fuel                    %>% 
             select(all_of(fuel_vars))     %>% 
             rename_at(vars(fates_fuel_notrunk:fates_fuel_cwd),rename_fun)

treat_fuel = fuel_df                                 %>% 
             filter(!case%in% c(1,5,9))              %>% 
             select(case,desc,time,
                    fates_fuel_notrunk,
                    fates_fuel_litter,
                    fates_fuel_cwd)
  
delta_fuel = cbind(treat_fuel,ctrl_fuel)

delta_fuel = delta_fuel                    %>% 
             mutate(site=site_grab(desc))

delta_fuel$treatment = unlist(lapply(delta_fuel$desc,treatment_grab))


for(v in sequence(n_fuel)){
  var_now = fuel_vars[v]
  delta_fuel[[var_now]] = delta_pct_fun(delta_fuel,var_now,1,0)
}

delta_fuel =  delta_fuel           %>% 
              mutate_at(vars(fates_fuel_notrunk:fates_fuel_cwd),
                        zero_to_na)
       
deltafuel_mean   = NULL
deltafuel_se     = NULL

for(n in treated_case){
  delta_now = delta_fuel %>% filter(case==n)
  if(n %in% c(2:4)){
    fst_yr = 2001
    lst_yr = 2003
  }else if(n %in% c(6:8)){
     fst_yr = 2011
     lst_yr = 2011
  }else if(n %in% c(10:12)){
    fst_yr = 2003
    lst_yr = 2003
  }
  mean_fuel  = delta_now                                            %>% 
              mutate(year=year(time))                               %>% 
              filter(year%in%c(fst_yr,lst_yr))                      %>% 
              select(-c(time,case,desc,year))                       %>% 
              group_by(site,treatment)                              %>% 
              summarize_all(mean,na.rm=TRUE)
    
  deltafuel_mean = rbind(deltafuel_mean,mean_fuel)
    
  se_fuel  = delta_now                                             %>%
             mutate(year=year(time))                               %>% 
             filter(year%in%c(fst_yr,lst_yr),
                    !is.na(fates_fuel_notrunk))                    %>% 
             select(-c(time,case,desc,year))                       %>% 
             group_by(site,treatment)                              %>% 
             #summarize_all(sd,na.rm=TRUE)
             summarize_all(funs(se=sd(.)/sqrt(n())))
  deltafuel_se = rbind(deltafuel_se,se_fuel)
    
}

mod_deltafuel = deltafuel_mean                         %>% 
                select(site,treatment,
                       fates_fuel_notrunk,
                       fates_fuel_litter,
                       fates_fuel_cwd)                 
               
mod_deltafuel_se = deltafuel_se                        %>% 
                   select(site,treatment,
                          fates_fuel_litter_se,
                          fates_fuel_notrunk_se,
                          fates_fuel_cwd_se)            
                  
mod_deltafuel = mod_deltafuel %>% left_join(mod_deltafuel_se, by=c("site","treatment"))
mod_deltafuel = mod_deltafuel                           %>% 
                mutate(type = case_when(treatment=="Burn-Cool" ~ "Model-BurnCool",
                                      treatment=="Burn-Hot" ~ "Model-BurnHot",
                                      treatment=="Thin" ~ "Model-Thin"),
                      treatment = ifelse(treatment %in% c("Thin","None"), treatment, "Burn"))

obs_deltafuel = obs_fuel                               %>% 
                filter(Year %in% c(2003,2014),
                      Fuel_class %in% c("BROWNS_FOREST_FLOOR",
                                        "Total_1_10_100_hr_fuels",
                                        "Litter") &
                        Treatment %in% c("Burn","Thin"))  %>% 
                select(site,Treatment,Fuel_class,
                       percent_diff,se_percent_diff)   %>% 
                pivot_wider(names_from=Fuel_class,
                            values_from=c(percent_diff,se_percent_diff)) %>% 
                rename(fates_fuel_notrunk = percent_diff_BROWNS_FOREST_FLOOR,
                       fates_fuel_notrunk_se = se_percent_diff_BROWNS_FOREST_FLOOR,
                       fates_fuel_cwd = percent_diff_Total_1_10_100_hr_fuels,
                       fates_fuel_cwd_se = se_percent_diff_Total_1_10_100_hr_fuels,
                       fates_fuel_litter = percent_diff_Litter,
                       fates_fuel_litter_se = se_percent_diff_Litter,
                       treatment = Treatment) %>% 
                mutate(type = "Observation")


mod_deltafuel = rbind(mod_deltafuel, obs_deltafuel)
plot_vars = fuel_vars
plot_desc = fuel_desc
n_plot = length(fuel_vars)
for(n in sequence(n_plot)){
  var_now = plot_vars[n]
  desc_now = plot_desc[n]
  se_var = paste0(var_now,"_se")
  gg_now = ggplot(mod_deltafuel,aes_string(x="treatment",y=var_now,fill="type")) 
  gg_now = gg_now + geom_bar(position=position_dodge(),stat="identity",width=0.6) 
  if(n==1){
     gg_now = gg_now + geom_errorbar(aes(ymin=fates_fuel_notrunk - fates_fuel_notrunk_se,
                         ymax=fates_fuel_notrunk + fates_fuel_notrunk_se),
                     width=0.2,
                     position=position_dodge(0.6))
  }else if(n==2){
     gg_now = gg_now + geom_errorbar(aes(ymin=fates_fuel_litter - fates_fuel_litter_se,
                         ymax=fates_fuel_litter + fates_fuel_litter_se),
                     width=0.2,
                     position=position_dodge(0.6))
    
  }else if(n==3){
    gg_now = gg_now + geom_errorbar(aes(ymin=fates_fuel_cwd - fates_fuel_cwd_se,
                         ymax=fates_fuel_cwd + fates_fuel_cwd_se),
                     width=0.2,
                     position=position_dodge(0.6))
    
  }
 
  gg_now = gg_now + facet_wrap(.~site,ncol=3)
  gg_now = gg_now + scale_fill_manual(values=c("Model-BurnCool" = "#836B43",
                                               "Model-BurnHot" = "#D68D18",
                                               "Model-Thin" = "#A0AE6A",
                                               "Model-Control" = "#18B0D6",
                                               "Observation" = "#437683"))
  gg_now = gg_now + ylab(paste("Relative change in", desc_now, "(%)",sep=" "))
  gg_now = gg_now + xlab("") 
  gg_now = gg_now + theme_grey( base_size = gg_ptsz, base_family = "Helvetica",
                                base_line_size = 0.5,base_rect_size =0.5) 
  gg_now = gg_now + theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm")
                                              , angle = 90
                                              , hjust = 1)#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

 for (d in sequence(ndevice)){
    f_output = paste0(var_now,"_delta_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = gg_now
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.6
                    , height   = gg_height*0.8
                    , units    = gg_units
                    , dpi      = gg_depth
                    )
   }
}







            

```





```{r PrePostFuelBenchmark}


## Teakettle

mod_prethin_fuel_tea = fuel_df                       %>% 
                      mutate(year = year(time),
                             month = month(time))    %>% 
                      filter(year == 2001 &
                             month == 1 &
                             case == 10)              %>% 
                      select(case,desc,
                      fates_fuel_cwd,
                      fates_fuel_notrunk)             %>% 
                      group_by(case,desc)             %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                      

mod_prerx_fuel_tea = fuel_df                         %>% 
                      mutate(year = year(time),
                             month = month(time))    %>% 
                      filter(year == 2001 &
                             month %in% c(1:4) &
                             case %in% c(11:12))      %>% 
                      select(case,desc,
                             fates_fuel_cwd,
                             fates_fuel_notrunk)      %>% 
                      group_by(case,desc)             %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       
                      

mod_postthin_fuel_tea = fuel_df                      %>% 
                      mutate(year = year(time))      %>% 
                      filter(year %in% c(2002:2003) &
                             case == 10 )             %>% 
                      select(case,desc,
                             fates_fuel_cwd,
                             fates_fuel_notrunk)      %>% 
                      group_by(case,desc)             %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       %>% 
                      rename_at(vars(fates_fuel_cwd:
                                     fates_fuel_notrunk),
                                post_rename)

mod_postrx_fuel_tea = fuel_df                         %>% 
                      mutate(year = year(time))       %>% 
                      filter(year %in% c(2002:2003) &
                             case %in% c(11:12))      %>% 
                      select(case,desc,
                             fates_fuel_cwd,
                             fates_fuel_notrunk)      %>% 
                      group_by(case,desc)             %>% 
                      summarize_all(mean,na.rm=TRUE)  %>% 
                      ungroup()                       %>% 
                      rename_at(vars(fates_fuel_cwd:
                                     fates_fuel_notrunk),
                                post_rename)

mod_pre_fuel = rbind(mod_prethin_fuel_tea,mod_prerx_fuel_tea)
mod_post_fuel = rbind(mod_postthin_fuel_tea, mod_postrx_fuel_tea)

mod_prpo_fuel = mod_pre_fuel %>% left_join(mod_post_fuel,by=c("case","desc"))

prpo_vars = names(mod_prpo_fuel)[grepl("fates_",names(mod_prpo_fuel))]
n_var = length(prpo_vars)
for(n in sequence(n_var)){
  var_now = prpo_vars[n]
  mod_prpo_fuel[[var_now]] = prepost_pct_diff(mod_prpo_fuel,var_now)
  
}
mod_prpo_fuel = mod_prpo_fuel %>% mutate(site=site_grab(desc))
mod_prpo_fuel$treatment = unlist(lapply(mod_prpo_fuel$desc,treatment_grab))
mod_prpo_fuel$fates_fuel_cwd_se = NA
mod_prpo_fuel$fates_fuel_notrunk_se = NA
mod_prpo_fuel = mod_prpo_fuel                       %>% 
                mutate(type = case_when(treatment=="Burn-Cool" ~ "Model-BurnCool",
                                        treatment=="Burn-Hot" ~ "Model-BurnHot",
                                        treatment=="Thin" ~ "Model-Thin",
                                        treatment=="None" ~ "Model-Control"),
                                        treatment = ifelse(treatment %in% c("Thin","None"), treatment, "Burn"))
mod_prpo_fuel = mod_prpo_fuel %>% select(site,treatment,fates_fuel_cwd,type)
 
obs_prpo_fuel = fread(file.path(obs_path,"prepost-fuel-obs.csv"))


obs_prpo_fuel = obs_prpo_fuel               %>% 
              filter(Fuel_class == "Total_1_10_100_hr_fuels" &
                     Treatment != "Burn+Thin") %>% 
              select(site,Treatment,
                     PrePost_pct_diff)         %>% 
              rename(treatment = Treatment,
                     fates_fuel_cwd = PrePost_pct_diff)



obs_prpo_fuel = obs_prpo_fuel              %>% 
                  mutate(type = "Observation")

mod_prpo_fuel = rbind(mod_prpo_fuel,obs_prpo_fuel)

plot_df =mod_prpo_fuel

gg_now = ggplot(plot_df,aes(x=treatment,y=fates_fuel_cwd,fill=type)) 
gg_now = gg_now + geom_bar(position=position_dodge2(),stat="identity",width=0.6)
#gg_now = gg_now + geom_errorbar(aes(ymin=fates_nplant - fates_nplant_se,
#                         ymax=fates_nplant + fates_nplant_se),
#                     width=0.2,
#                     position=position_dodge(0.6),stat="identity")
gg_now = gg_now + facet_wrap(.~site,ncol=1)
gg_now = gg_now + scale_fill_manual(values=c("Model-BurnCool" = "#836B43",
                                             "Model-BurnHot" = "#D68D18",
                                             "Model-Thin" = "#A0AE6A",
                                             "Model-Control" = "#18B0D6",
                                             "Observation" = "#437683"))
gg_now = gg_now + ylab("Pre-post change in CWD fuel load ( % )")
gg_now = gg_now + xlab(" ") 
gg_now = gg_now + theme_grey( base_size = gg_ptsz, base_family = "Helvetica",
                                base_line_size = 0.5,base_rect_size =0.5) 
gg_now = gg_now + theme( legend.title =element_blank()
            , legend.position="bottom"
            , legend.box = "vertical"
            , legend.margin = margin()
            , axis.text.x       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            , axis.text.y       = element_text( size   = gg_ptsz
                                              , margin = unit(rep(0.35,times=4),"cm"))#end element_text
            )#end theme+

for (d in sequence(ndevice)){
    f_output = paste0("cwd_prepost_benchmark.",gg_device[d])
    dummy    = ggsave( filename = f_output
                    , plot     = gg_now
                    , device   = gg_device[d]
                    , path     = bncmark_path
                    , width    = gg_widthn*0.55
                    , height   = gg_height*0.65
                    , units    = gg_units
                    , dpi      = gg_depth
    )
    }






```

