---
title: "Site-climate-monthly-mean"
author: "Xiulin Gao"
date: "Feb-04-2025"
output: html_notebook
---
this script takes WRF hourly forcing data (file split by month), extract the nearest point, and plot historical climate trend for selected sites. 

```{r, label="load-packages", include=FALSE}
library(ncdf4)
library(lubridate)
library(tidyverse)
library(data.table)
library(ggplot2)

```




```{r,label="constant"}
K_2_degC  = -273.15
hr_2_sec  = 3600
day.hr    = 24
day.min   = 1440
day.sec   = 86400

```




```{r,label="plot-settings"}
gg_device  = c("png")     # Output devices to use (Check ggsave for acceptable formats)
gg_depth   = 600          # Plot resolution (dpi)
gg_ptsz    = 18           # Font size
gg_ptszl   = 26
gg_width   = 17.5         # Plot width (units below)
gg_widthn  = 14.5
gg_height  = 8.5          # Plot height (units below)
gg_units   = "in"         # Units for plot size
gg_screen  = FALSE         # Show plots on screen as well?
gg_tfmt    = "%Y"         # Format for time strings in the time series %Y: 4 DIGITS YEAR %y 2 digits year
gg_ncolours    = 129      # Number of node colours for heat maps.
gg_fleg        = 1./6.    # Fraction of plotting area dedicated for legend
gg_dstat_thick = 0.1      # Thickess for the drought-deciduous status band in the stress overview plot (Value
ndevice = length(gg_device)


ens_colour = c("#A0AE6A", "#836B43", "#D68D18", "#437683", "#18B0D6")

```



```{r, label="path-setting"}
in_path    = file.path('/glade/work/xiugao/fates-input/ca-wrf-grassland/CLM1PT_data')
out_path   = file.path('/glade/work/xiugao/fates-input/CZ2/CLM1P_data')
plot_path  = file.path("~/Sierra-mixedConifer-project/results")
wrfxy_path = file.path(in_path,'1981-01.nc')

wrf_files = list.files(in_path,pattern=".nc$")
nfile     = length(wrf_files)

yr_s      = 1951
yr_e      = 2020
n_yr      = yr_e - yr_s + 1
nc_year      = as.numeric(yr_s:yr_e)
nc_month     = as.numeric(1:12)
yr_each      = rep(nc_year,each=12)
month_each   = rep(nc_month, times=n_yr)
each_tstamp  = make_datetime(year=yr_each,month=month_each,day=1L, hour=0L)
dtime        = length(each_tstamp)

##time unit conversion

cmon.day = days_in_month(each_tstamp)
cmon.sec = day.sec * cmon.day



```





```{r, label="site-info"}

site_x = c(-120.0406,-122.49499,-122.6896,-122.6236)
site_y = c(34.6928, 38.00874, 38.5698,38.4292)
site_names = c("Sedgwick","China-Camp",
               "Pepperwood","Annadel")
nsites = length(site_names)

## read climate variables

clim_var = c("PRECTmms","TBOT") # in mm/s and K respectively 
nclim    = length(clim_var)

```



```{r, label="coordinates"}
targ_xy = data.frame(site_x,site_y)
wrf_dim  = nc_open(wrfxy_path)
wrf_x    = ncvar_get(wrf_dim,"LONGXY")
wrf_y    = ncvar_get(wrf_dim,"LATIXY")
x_vec    = as.vector(wrf_x)
y_vec    = as.vector(wrf_y)
wrf_xy   = data.frame(x_vec,y_vec)

```



```{r, label="find-the-nearest-point"}
find_nnxy = function(targ,ref){
  nn_pt = RANN::nn2(ref[,1:2],targ[,1:2],k=1)
  nn_idx = as.vector(nn_pt$nn.idx)
  ref_xy = ref[nn_idx,]
  return(ref_xy)
}

```



```{r,label="extrac-clim-NN"}

site_clim   = as_tibble( matrix(   data  = NA
                              , nrow     = dtime * nsites
                              , ncol     = nclim + 1
                              , dimnames = list(NULL,c("site",clim_var))
                         ))

for (n in seqence(nsites)){
  targ_now = targ_xy[n,]
  site_now = site_names[n]
  nn_wrf = find_nnxy(targ_now,wrf_xy)
  wrf_nnidx1 = which(wrf_x==nn_wrf$x_vec,arr.ind=TRUE)
  wrf_nnidx2 = which(wrf_y==nn_wrf$y_vec,arr.ind=TRUE)
  sprintf("nearest point indices found in WRF is %s and %s", wrf_nnidx1[1:2], wrf_nnidx1[1:2])
  wrf_nnidx = wrf_nnidx1
  
  for (f in sequence(nfile)){
    file_now = wrf_files[f]
    path_now = file.path(in_path,file_now)
    nc_now   = nc_open(path_now)
    
    if(n==1){
          site_clim$site[[f]] = site_now
          }
      else{site_clim$site[[(n-1)*dtime + f]] = site_now
          }
    
    for (c in sequence(nclim)){
      clim_now = clim_var[c]
      df_now   = ncvar_get(nc_now, varid = clim_now)
      df_now   = df_now[wrf_nnidx[1],wrf_nnidx[2],]
      ## calculate daily mean temp and precipitation by doing
      ## a running mean with moving window of 24 as it's hourly data
      df_now = frollmean(df_now, n=24)
      ## then monthly mean by average df_now
      df_now = mean(df_now,na.rm=TRUE)
      
      if(n==1){
          site_clim[[clim_now]][[f]] = df_now}
      else{
          site_clim[[clim_now]][[(n-1)*dtime + f]] = df_now
      }
    }
     dummy  = nc_close(nc_now)
  }#end of for (f in sequence(nfile))
  
} #end of for (n in n in sequence(nsites))

site_clim = site_clim %>% mutate(TBOT = TBOT + K_2_degC)
site_clim$time = rep(each_tstamp,times=nsites)

file_name = paste0("climate-by-sites.csv")
fwrite(site_clim,file.path(out_path,file_name))

```



```{r,label="monthly-mean"}

site_clim$mon_sec = rep(cmon.sec,times=nsites)

mmean = site_clim                            %>% 
        mutate(month = month(time),
               PRECTmms = PRECTmms*mon_sec)  %>% 
        group_by(site,month)                 %>% 
        select(-time)                        %>% 
        summarize_all(mean,na.rm=TRUE)       %>%
        rename(rain =  PRECTmms,
               temp = TBOT)                  %>% 
        ungroup()

```





```{r,label="plot-site-monthly-climate"}

plot_var = c("temp","rain")
nplot = length(plot_var)

for(p in sequence(nplot)){
  var_now = plot_var[p]
  plot_now = ggplot(mmean, aes_string("month",var_now,colour="site")) 
  plot_now = plot_now + geom_line(linewidth=1.5) 
  plot_now = plot_now + scale_x_continuous( breaks = sequence(12)) 
  plot_now = plot_now + xlab("Month") 
  if(var_now=="temp"){
      plot_now = plot_now + ylab(expression("Temperature ("*~degree*C*")"))}else{
      plot_now = plot_now + ylab(expression("Precipitation ("~mm~month^-1~")"))
      }
  plot_now = plot_now + scale_color_manual(values = ens_colour) 
  plot_now = plot_now + theme_grey( base_size = gg_ptsz, 
                                    base_family = "Helvetica",
                                    base_line_size = 0.5,
                                    base_rect_size =0.5)
  plot_now = plot_now + theme(legend.position   = "right"
                            , axis.text.x       = element_text( size   = gg_ptsz
                                                  , margin = unit(rep(0.35,times=4),"cm")
                                                   )#end element_text
                            , axis.text.y       = element_text( size   = gg_ptsz
                                                  , margin = unit(rep(0.35,times=4),"cm")
                                                  )#end element_text
                            , plot.title        = element_text( size = gg_ptsz)
                            , axis.ticks.length = unit(-0.25,"cm")
                )#end theme

 for (d in sequence(ndevice)){
    f.output = paste0("site-monthly-",var_now,".",gg_device[d])
    dummy = ggsave( filename = f.output
                  , plot     = plot_now
                  , device   = gg_device[d]
                  , path     = plot_path
                  , width    = gg_widthn*0.5
                  , height   = gg_height*0.5
                  , units    = gg_units
                  , dpi      = gg_depth
                  )#end ggsave
  }#end for (o in sequence(nout))
      


}



```

